### ISSUE TITLE
Implement "Linked Dictionaries"(Editing a concept referenced in a collection should automatically update the reference)

### ISSUE THREAD

**Issue by brucemakallan** [OpenConceptLab/ocl_issues#100]
When a Concept is edited, its corresponding reference in a Collection/Dictionary is not updated.

**Comment by djazayeri** [comment]
Key point to call out: creating/editing a concept in the source and updating the linked collection (with associated validations) should be done atomically.

For example:

1. Hospital X Dictionary (collection) uses OpenMRS validation scheme
2. Hospital X Dictionary (collection) includes a reference to the CIEL concept "Malaria".
3. User creates/edits a concept in Hospital X Custom Concepts (source) and names it "Malaria"

Expected behavior: step 3 should fail (because this would mean adding this new/edited concept to the collection, but the collection already includes a concept with an identical name, thus OpenMRS validation will fail on the collection.

**Comment by Karuhanga** [comment]
Hey @djazayeri, @paynejd,
Will it make sense to include this in the core(linking a source and collection)? Or should this issue be closed.

**Comment by paynejd** [comment]
I think this would be valuable as a core feature. To start, could you write
out (in this ticket is fine) exactly how this feature works in the OCL for
OMRS client and any changes in how you would want it to work if implemented
in the core API? Thanks @karuhanga!

**Comment by Karuhanga** [comment]
Currently, the way this works is we abstract the concept of a `source` and `collection` into a `dictionary` and whenever a user updates a concept in the source, we delete the reference of that concept in the collection and add the concept again(latest version).

We do this for mappings as well. So if a user updates mappings in a concept, we do the same thing for each mapping.

**Comment by paynejd** [comment]
This is an important feature for all OCL users, including the OpenMRS squad. We will discuss on an upcoming OCL Architecture call and add to the roadmap after the oclapi2 launch.
