### ISSUE TITLE
Fix About page to match Overview - Markdown and HTML stylings should match

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1017]
The Markdown styling (used in Text - Markdown tabs) and HTML styling (used in About tabs) seem different, including font size for headings and the spacing on the left side of the text. Can these be aligned so that they look consistent? 

Markdown:
![image](https://user-images.githubusercontent.com/55999682/135618212-95cae18c-727c-46c6-8cac-51a8bc78d30d.png)

HTML:
![image](https://user-images.githubusercontent.com/55999682/135618238-6db48ecc-7a3f-40a4-b55c-3b675d9da5c7.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri I have aligned the left spacing to be consistent with About.
The size of heading and other things comes from MD format.
For example in the above screenshot the first heading has `#` single that means h1, while for about we use h3 which is smaller. Either you can change the MD file to have `###` instead of `#` or I can change the About to use `h1`.

**Comment by paynejd** [comment]
Please change about header to `h1`

**Comment by jamlung-ri** [comment]
These are now matching in QA.
