### ISSUE TITLE
Easy nav to Favorite/Pinned content

### ISSUE THREAD

**Issue by gracepotma** [OpenConceptLab/ocl_issues#1059]
As a user reviewing content in OCL, I need it to be easy to go back to a **favorite** org/source/collection/concept, so that I don't have to spend so much time/clicks navigating through the app to go back to a **favorite** org/source/collection/concept. (The other solution is that I can have a large # of tabs open.)

I believe we could use "pins" the same way as "favorites" (because they have similar semantics: this thing is more important to the user than others).

Suggestion: Perhaps we could have a direct one-click navigation to the user's pinned items, via something in the global nav, like this example below. (After a while I realized I can kind of get to my pinned content by clicking my user icon in the top right, then by clicking "my profile", but this doesn't feel intuitive and I'd like it to be one quick click.) Idea is that when the user clicks the pin, we could take them to a page that shows them a list of all their pinned content. 
 
![image](https://user-images.githubusercontent.com/67400059/138792832-97b5532d-15b5-47a8-9338-ede99b7503d1.png)

This came up in the same user testing mentioned in issue #1058.

**Comment by jamlung-ri** [comment]
@snyaggarwal This is partially working, since I can get to my user account's pinned repos. However, it appears that these pins only work for content that a user owns. I believe the overall intent for this was to be able to "pin" any organization's content and get to it quickly. For example, as a new user, I might try to pin LOINC and CIEL since I access those the most, even though I am not the owner of the content. That said, this seems more like a "favorite" function than a "pin" function. Maybe we should create another ticket specifically for favorite-ing orgs and repos?

**Comment by snyaggarwal** [comment]
@jamlung-ri This comes down to the functionality of what can a user pin?
1. A user can pin any org that s/he is a member of.
2. Any sources/collections under the user's scope.
3. Admin can pin any source/collection on org's home.

Will probably have to change that. This Pinned/Favorite panel shows anything that is pinned by the user.

**Comment by snyaggarwal** [comment]
@jamlung-ri And I agree that this is not the "favorite" feature. Favorite can be anything irrespective of you are a member or not.

**Comment by jamlung-ri** [comment]
Gotcha, that makes sense. I think that's something worth pursuing in the future, so I can create a ticket for that. For now, Pinning seems to be working as you described.
