### ISSUE TITLE
Concept $cascade Hierarchy Visualization

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1169]

**Comment by snyaggarwal** [comment]
- [x] $cascade visualization on Concept Home in "Associations" section
- [ ] Source Concepts Table hierarchy view

**Comment by snyaggarwal** [comment]
- [ ] Show Map types 
- [ ] Add mappings with target concepts not in OCL

**Comment by paynejd** [comment]
These are not all required, but worth considering as a final round of changes before pushing this new feature to production:
- Clicking on the node should expand/collapse the node
- Clicking on the ID should navigate to the concept (maintaining the spot in the visualization would be nice, if possible)
- If a mapping points to a concept in another source, the concept ID should include the source ID, e.g. “ICD-10 / H15.8”
- Different node types should look different:
  - Collapsed node that has children – square with a plus inside?
  - Expanded node that has children – square with a minus inside?
  - Terminal node (that we know has no children) – maybe a solid circle?
  - Terminal node (that we don’t know whether or not it has children, e.g. it is in another source) — a transparent circle with just a border?
- Levels ⇒ “1” actually results in 2 levels being displayed (cascade plus 1 level of recursion); instead, Levels should indicate the number of levels beyond the selected concept, so let’s subtract one from this before displaying it
- “Forward/Backward” dropdown:
  - By default, can we do both forward and backwards at the same time?
    - Maybe only to ~2 levels deep each way?
    -  This could be done using a Range slider that uses discrete ticks
  - If not, when going Backward, we want our initial concept to be on the right, and its negative cascade levels can be shown on the left
- Visualization should focus/scroll by default onto the concept that is being viewed
- Add the “Beta” text to the icon
- Filters should consolidate into a dropdown menu when width is reduced so that we don’t end up like this:
![image](https://user-images.githubusercontent.com/1189689/149530275-395e4733-f69c-4250-b1b7-3c0981c04e44.png)

**Comment by snyaggarwal** [comment]
Following are done:
- Clicking on the node should expand/collapse the node
- If a mapping points to a concept in another source, the concept ID should include the source ID, e.g. “ICD-10 / H15.8”
- Levels ⇒ “1” actually results in 2 levels being displayed (cascade plus 1 level of recursion); instead, Levels should indicate the number of levels beyond the selected concept, so let’s subtract one from this before displaying it
- Add the “Beta” text to the icon
- Filters should consolidate into a dropdown menu when width is reduced so that we don’t end up like this:

**Comment by snyaggarwal** [comment]
Terminal indicator is also added

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri Can this be closed?

**Comment by jamlung-ri** [comment]
I think it's fine to close it for now, and we can create follow-up tickets as needed.
