### ISSUE TITLE
Dev Environment: DELETEs take a long time

### ISSUE THREAD

**Issue by ibacher** [OpenConceptLab/ocl_issues#1175]
In the Dictionary Manager E2E tests, we create and delete collections and sources fairly frequently, essentially ensuring that each test runs against a completely clean dictionary. Most of these collections and sources are quite small—on the order of no more than 3 concepts and maybe 20-odd references. However, when we make a `DELETE` request to the API, it now takes >60s to get a response back from the server when deleting the source, even in cases where the source is actually empty (because there are no custom concepts or custom references).

I can understand that there might be some additional processing that needs to go on in the background but, for our purposes, it actually isn't important to know when the `DELETE` was completed, simply that it will be at some point. Is there some way we could add an asynchronous request to delete a source, i.e., something that will kick-off the longer running process without requiring the client to wait?

**Comment by paynejd** [comment]
flagging as high priority for @snyaggarwal

**Comment by snyaggarwal** [comment]
@ibacher @paynejd The delete was generally slow because it was trying to delete everything in sync as @ibacher pointed out correctly. The major culprit was clearing out cached exports, which is now async.
I just deleted a new style collection from DEV environment in ~300ms.
Also this change is done on master as well (deployed to QA).
Do let me know how it feels.

**Comment by ibacher** [comment]
This feels much better to me! THanks @snyaggarwal!
