### ISSUE TITLE
Implement global $resolveReferences operation

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1195]
Related to BMGF 1.2b: Implement the ability to specify OCL collection references using FHIR-formatted canonical URLs, in addition to the already-supported OCL native format.

First step is requirements, documented here: https://docs.google.com/document/d/1zrQOQBC868uRdrZA-mhzvNzsepVYFhHrMDuJU7mKRjY/edit#

**Comment by paynejd** [comment]
With the first version of the `$resolveReference` operation (see #1221) nearly ready, we're ready to implement support for canonical URLs as collection references.

* Resolution of collection references should utilize the new `$resolveReference` operation internally so that this logic can be implemented in only one place and we can migrate everything over to use it over time.
* Collection references should be processed from the namespace of the collection -- meaning for a collection `/orgs/MyOrg/collection/MyCollection/`, the references should be processed using the `/orgs/MyOrg/` namespace
* Relative URLs are always evaluated the same regardless of namespace, so the handling of the all existing collection references should be unaffected by the change, except for one big thing!
  * Version-less references will now resolve to `latest` instead of `HEAD`!
  * IDEA: Add an internal switch in $resolveReference that is set to resolve version-less "relative URLs" to `HEAD` that we can change to `latest` when we're ready -- note that version-less "canonical URLs" should always resolve to `latest` (this was added to #1221)
* Evaluation of Canonical URLs changes based on namespace, so these references will generally not resolve after this first round of work unless the canonical is explicitly defined for a released source/collection version in the namespace

This fits into the same `"data": [...]` format that OCL currently supports. Some examples (not comprehensive):
* Current model - single expression:
  * Concept from source version: `"/orgs/CIEL/sources/CIEL/v2021-03-12/concepts/1948/"`
  * Specific concept version: `"/orgs/CIEL/sources/CIEL/concepts/1948/123/"`
  * Version-less concept (OCL resolves to latest when evaluated): `"/orgs/CIEL/sources/CIEL/concepts/1948/"`
* Expanded model - relative URLs:
  * Concept from source version:
    * `{"url": "/orgs/CIEL/sources/CIEL/v2021-03-12/", "code": "1948"}`
    * `{"url": "/orgs/CIEL/sources/CIEL/", "version": "v2021-03-12", "code": "1948"}`
  * Version-less Concept (resolves to latest): `{"url": "/orgs/CIEL/sources/CIEL/", "code": "1948"}`
  * Specific concept version: `{"url": "/orgs/CIEL/sources/CIEL/concepts/1948/123/"}`
* Expanded model - canonical URLs -- note that namespace is set automatically to the collection's namespace when processing these:
  * Concept from source version:
    * `{"url": "http://worldhealthorganization.github.io/ddcc/ConceptMap/WHO_DDCC_Map_ICD11_to_SCT_Disease_Targeted", "version": "v1", "code": "123"}`
    * `{"url": "http://worldhealthorganization.github.io/ddcc/ConceptMap/WHO_DDCC_Map_ICD11_to_SCT_Disease_Targeted|v1", "code": "123"}`
  * Version-less Concept (resolves to latest): `{"url": "http://worldhealthorganization.github.io/ddcc/ConceptMap/WHO_DDCC_Map_ICD11_to_SCT_Disease_Targeted", "code": "123"}`
