### ISSUE TITLE
Concept/Mapping Split View

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1203]
Tasks:
- Use Paul's new split view design (from zeplin)
- in Source/Collection home concept/mapping listing on select from checkbox open split view
- in Source/Collection home concept/mapping listing on right click (double tap) open split view
- in Global Search on right click open split view
- Remove Concept/Mapping row expansion
- Remove explicit Split View option in layout filters
- Make Width adjustable on drag
- Make left and right to scale/shrink gracefully using grid design

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd Everything in this is deployed on QA. Do let me know here any feedback/bugs.

**Comment by jamlung-ri** [comment]
A couple of things:

- [ ] Associations section of the Split View seems to not be showing parent relationships (see Split View for A19 [here](https://app.qa.openconceptlab.org/#/orgs/WHO/sources/ICD-10-WHO/), and its concept details page [here](https://app.qa.openconceptlab.org/#/orgs/WHO/sources/ICD-10-WHO/concepts/A19/))

- [ ] Once we are settled on the Split View, I think we want to retire the concept details page. Not sure if that's a near term thing or if we need more time. @paynejd Welcoming your input on this one.

**Comment by paynejd** [comment]
Regarding "concept/mapping details" view ---

I imagined that if a user receives a direct link to a resource, that it
would still open the resource in the split view but with the left pane
completely minimized. If a user expands the left pane, then it would load
the relevant repository on the corresponding resource search page. This
approach would allow us to eliminate the dedicated resource details view.

**Comment by snyaggarwal** [comment]
@jamlung-ri I have added styles to filter options as per Pauls' recommendation.
Let me know how it looks on QA.

**Comment by jamlung-ri** [comment]
Looking good! Scrolling works well, and I can apply lots of filters and still get to all of them.

Slight issues and feedback:
- [ ] Are we in a good spot to remove the Include Retired filter chip, since it is reflected in the More Filters pane? If we're feeling ambitious, maybe the Last Updated chip could also be moved to the More Filters pane, but I don't want to push too hard if it's too difficult.
- [ ] There is some overlap between the panes and the Share button, at least on my screen. See image: 
![image](https://user-images.githubusercontent.com/55999682/156597039-b879d288-1ba0-4518-b0a0-06c0886922e0.png)

Other feedback we may want to save for discussion with Paul (not yet ready for development)
- The breadcrumb that now shows the source versions and concept versions might be a little complicated, because it looks like we are going multiple layers in. I wonder if there's a nice way to show the version information somewhere with the breadcrumb, but in a more concise way.
![image](https://user-images.githubusercontent.com/55999682/156598600-19a65462-8f04-4c01-9a62-6d6127a33f49.png)

**Comment by snyaggarwal** [comment]
1. @jamlung-ri Include Retired Chip and the retired in filters serves different purposes -- Include Retired Chip adds retired results in addition to the regular results. Retired check in filter shows just retired entries. Not sure if we want to keep both?
2. @jamlung-ri I am unable to reproduce the issue you mentioned with split view, can you mention screen size, resolution and browser here to help me reproduce this?

**Comment by jamlung-ri** [comment]
1. @snyaggarwal Assuming we can check both of these retired filters (i.e. filter for Retired=True OR Retired=false), then that should do the same thing as the Retired Chip, correct?
    - That said, I notice that checking both of them does not seem to yield more results in the Global search. See this image as an example:
![image](https://user-images.githubusercontent.com/55999682/157048435-fa4ac9ee-9de9-4610-89d7-39cb50ebddec.png)

2. @snyaggarwal I am using 1920 x 1080 resolution, full screen browser, and Firefox. I should have mentioned before that it **only** seems to be happening on a configured org that is showing Concepts/Mappings in a Split View. Example: https://app.qa.openconceptlab.org/#/orgs/PEPFAR-Test10b/?configs=true

**Comment by snyaggarwal** [comment]
@jamlung-ri 
1. I have updated the behaviour to allow true and false to be selected together and to work it like IncludeRetired. Removed IncludeRetired Chip. Removed More toggle.
2. Fixed this

**Comment by jamlung-ri** [comment]
That's all working well! I feel like the split view is in a really good place now. @paynejd Is there any other split view feedback that you have?

**Comment by jamlung-ri** [comment]
There has been a lot of progress in improving the UI. Much of the feedback that Sunny addressed is covered in [this document](https://docs.google.com/document/d/1-0TJozkeNBgNP_tI_hvurqrjjAgfCsA21ZzVIhcf8AU/edit#).

**Comment by paynejd** [comment]
This is moving into production along with the expansions work -- so hopefully next week!
