### ISSUE TITLE
Concept hierarchy tabular view with split view support

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1209]

**Comment by jamlung-ri** [comment]
A couple things I am noting with this:

- [ ]  Overall, the biggest thing we need to address is starting at the root concept of a source, rather than displaying all concepts that have a child. 
- [ ]  How do we feel about showing the same concept multiple times on the same screen? Example: 
![image](https://user-images.githubusercontent.com/55999682/153898237-0ced5d2f-0733-40d5-9554-4596e91f1ade.png)

- [ ] Looks like child concepts are currently not showing details other than the code. (See picture)
- [ ] Not sure how easy it would be to fix the sorting (i.e. sort A-Z instead of Z-A), but I imagine we will get feedback on that specifically.
- [ ] Need to be able to identify a terminal node i.e. a concept with no children (so that the table UI does not show an arrow for getting child concepts)

**Comment by snyaggarwal** [comment]
@jamlung-ri these are all added

**Comment by jamlung-ri** [comment]
Looking great! I think we can close this out for now and create new tickets if new issues arise.
