### ISSUE TITLE
Support for auto-ID and external ID generation for concepts/mappings

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#1210]
Using OCL for authoring of content requires that OCL support appropriate ID generation for newly created content. It's not sufficient to leave fields like concept ID and external ID as manual entry. When creating a new concept, a dictionary manager should be able to create a new concept and rely on auto-assignment of these identifiers.

Since the business rule for ID generation might vary between organizations and/or sources, the OCL platform will need to be able to support different algorithms for auto-assignment. While terminologies like LOINC would need fancier algorithms (e.g., check digit support), we could probably get everything we need at this point for the OpenMRS community if we create a few pre-baked algorithms that could optionally be configured for concept ID and/or external ID auto-assignment within a source:
  * [Version 4 (Random) UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random))
  * Next available integer within source (if 1, 2, 4, and 5 exist, the next value is 3)
  * Maximum concept ID + 1 (if 1, 2, 4, and 5 exist, the next value is 6)

Extra credit: while we are also relying on gold mappings (e.g., for PIH), it would be very helpful if a new concept also automatically could get a SAME-AS mapping to itself (e.g., when adding PIH 123, it automatically gets a SAME-AS mapping to PIH 123).

**Comment by jamlung-ri** [comment]
Next step is for OCL team to propose an approach, and we can propose and begin development

**Comment by paynejd** [comment]
We want to control auto-ID behavior for 4 source fields:
* Concept ID (mnemonic)
* Concept External ID
* Mapping ID (mnemonic)
* Mapping External ID

3 auto-ID behaviors supported:
* `Sequential` - Sequential mnemonic - specific to a source + resource type - this only applies to Concept/Mapping IDs (not external IDs)
  * This behavior is different than the currently implemented behavior for mappings, which simply assigns the resource ID to the mnemonic if it is not provided -- this must instead be a sequential mnemonic specific to the source and resource type
* `UUID` - Generated UUID
* `None` - No auto-assignment of ID

We want to introduce 4 new source-level fields so that source admins may control the behavior:
* `source.autoid_concept_mnemonic` - default: `None`
* `source.autoid_concept_external_id` - default: `None`
* `source.autoid_mapping_mnemonic` - default: `Sequential`
* `source.autoid_mapping_external_id` - default: `None`

Questions:
* If both mnemonic and external ID are set to `UUID`, should the be set to the same value?

**Comment by bmamlin** [comment]
> * If both mnemonic and external ID are set to `UUID`, should they be set to the same value? i.e. only generate a single UUID and assign it to both the mnemonic and external ID? @bmamlin

We don't have a use case for this. I don't know of any terminologies/dictionaries that use a UUID for the code (official "ID"), since these are typically viewed and/or used by humans, so my gut reaction would be to avoid a potentially unintuitive business rule like this – i.e., if both mnemonic and external ID are set to `UUID`, they each get their own random UUID. If synchronized assignment was ever needed in the future, I'd suggest handling this case more explicitly by setting mnemonic to `UUID` and external ID to `Mnemonic`.

**Comment by lnball** [comment]
This is related to uuid discussion, CIEL has specific uuids for concepts (concept id + AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) and not random.  Do you intend to keep this?

**Comment by bmamlin** [comment]
> This is related to uuid discussion, CIEL has specific uuids for concepts (concept id + AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) and not random. Do you intend to keep this?

@lnball these non-standard UUIDs are an artifact from the SQL Darius wrote to automate conversion of pre-1.6 concepts that @askanter creates in CIEL. Once @askanter starts creating concepts in new versions of OpenMRS or in OCL, new CIEL concepts will get standard UUIDs. There isn't any plan to convert existing UUIDs, but I wouldn't rely on CIEL always having predictable, non-standard UUIDs.

**Comment by bmamlin** [comment]
To clarify the use case for `Sequential`, it would be most helpful for OpenMRS implementers for this feature to mimic the autoincrement functionality of MySQL – i.e., an integer that automatically increments. There are problems with both of the originally suggested approaches:

| Approach | Problem |
|-|-|
| Next available integer within source (if 1, 2, 4, and 5 exist, the next value is 3) | As @jamlung-ri [pointed out earlier](https://github.com/OpenConceptLab/ocl_issues/issues/1210#issuecomment-1087669019), implementations sometimes purge an earlier concept and would prefer _not_ to reuse those earlier identifiers.  |
| Maximum concept ID + 1 (if 1, 2, 4, and 5 exist, the next value is 6) | Implementations often import some CIEL concepts directly and @askanter started CIEL concept IDs in the 60000 range to avoid competing for identifiers from the local autoincrement (typically in the low 1000s). If we jump to the max concept ID, implementations would start creating their new concepts with IDs in the range used by CIEL. |

The approach for `Sequential` that would work best for OpenMRS implementations would be an `autoincrement` integer that skips concept IDs that have been taken and that we can (rarely) adjust when needed.
* Next autoincrement integer, skipping ID(s) if already used (if 1, 2, 4, 5, and 60000 exist and autoincrement value is 4, the next value is 6 and, once used, the autoincrement is set to 7.
* If the implementation needs to skip to IDs starting at 100, they bug @snyaggarwal to change their source's autoincrement to 100 or – after @snyaggarwal gets tired of doing this manually – the owner of the source can see and change the source's autoincrement value.

A brand new source with `Sequential` IDs would start with autoincrement = 1 (making their first concept ID "1"). When we import an existing dictionary for Gondor and they have 1200 of their own concepts (with IDs in the range 1-1250) along with 500 CIEL concepts (with IDs 60000+), we would set the source's autoincrement to 1251.

**Comment by snyaggarwal** [comment]
@paynejd @bmamlin First cut of this is deployed on QA, with the following features.

#### TermBrowser (while creating a source)
- Can specify autoid_concept_mnemonic sequential or uuid (default None)
- Can specify autoid_concept_external_id sequential or uuid (default None)
- Can specify autoid_mapping_mnemonic sequential or uuid (default sequential)
- Can specify autoid_mapping_external_id sequential or uuid (default None)

#### API
- if autoid is not set -- it will work as it was working
- if autoid is set to uuid -- it will simply use uuid4 to generate the mnemonic
- if autoid is set to sequential -- it will generate the next number in sequence starting from 1 and skipping what already exists in that Source.

#### Tech details:
- When a source is created with autoid sequential we are creating a [Sequence in DB](https://www.postgresql.org/docs/current/sql-createsequence.html) for each autoid field (concept/mapping's mnemonic/external_id) starting from 1
- when concept/mapping is created it will ask for the next id, which will auto-increment the DB sequence 
- when a concept/mapping is hard deleted it will reset the sequence to deleted id
- when a source is hard deleted, it will auto-delete the sequences attached to it

#### Questions:
- Do we need to handle retired concept/mapping in any special way? (current implementation doesn't differentiate between retired or active ids)
-  Can a source be updated from sequential to uuid and/or uuid to sequential? (currently, I have disabled this in TermBrowser in Edit Source)
- Should we provide a feature in TermBrowser (and edit source API) to set the sequence manually to a specific number?

**Comment by lnball** [comment]
I'd love to test this out.  Is it deployed?  What's the URL?

As for @snyaggarwal questions, 

- I don't care about the mappings for retired concepts.
- Don't think PIH will use the sequential uuids
- Could be helpful to set the concept id manually

**Comment by snyaggarwal** [comment]
#### From Dev Call yesterday:

- [x] Do not reset sequence on delete or concept/mapping since 
    - hard deletes are rare
    - Also an admin can set a concept/mapping id to the skipped (or deleted) number in sequence
- [x] Source edit should not allow editing of autoid attributes (current state)
- [ ] Concept/Mapping creation form should indicate what will be the nature of id (may be a tooltip or some indicator to differentiate between empty field vs filled)
- [x] From TermBrowser user should be able to specify start number for autoid and can edit this any time.

**Comment by askanter** [comment]
I am not sure what is actually being populated by autoID, since I would have thought that like patientIDs, there are either sequential integers (way we do it mostly now) or sequential formatted numbers that follow some sort of grammar. I don't see how you can practically use a UUID for a concept identifier plus every concept has a UUID as well, correct?

As for mappings on retired concepts... this might need to be thought through a little. My inclination is to keep mappings on retired concepts. If there is instance data attached to those concepts, they may still need maps to SNOMED, ICD, etc. as well as eventually a map to the replacement concept.

**Comment by bmamlin** [comment]
Looks great!

<img width="825" alt="image" src="https://user-images.githubusercontent.com/860834/172181265-d76448f0-ba27-436e-8b57-4bbca582bc17.png">

When mnemonics and external IDs are auto-assigned, we should encourage users to use the auto-assignment by default. To this end, could we adapt this UI so "Concept ID" and "External ID" input fields are replaced with something like:

> Concept ID will be auto-assigned (<ins>click here</ins> to override with manual entry)

where the user would have to go out of their way to reveal the input field when an ID is configured for auto-assignment. If they clicked for manual entry, the input field would be shown along with an <ins>auto-assign</ins> link to hide the input field and go back to using auto-assignment.

**Comment by snyaggarwal** [comment]
@bmamlin Added

**Comment by jamlung-ri** [comment]
Looking good to me! One tiny UI tweak that's coming as a result of using UUIDs as the Concept Mnemonic: the long ID should probably get truncated in the breadcrumb. See example below where a `...` would be helpful at the end of the ID in the breadcrumb: 
![image](https://user-images.githubusercontent.com/55999682/172411970-76af89d5-4aa1-4775-8607-4a0a7726a149.png)

**Comment by paynejd** [comment]
Joe's comment brings up an important point: UUIDs as a mnemonic should
actually not be encouraged -- the idea of a mnemonic is a human-usable
identifier. We can support auto-assignment of UUID, but we should make it
an un-happy path in the UI

**Comment by snyaggarwal** [comment]
added ellipsis.

**Comment by jamlung-ri** [comment]
> Joe's comment brings up an important point: UUIDs as a mnemonic should actually not be encouraged -- the idea of a mnemonic is a human-usable identifier. We can support auto-assignment of UUID, but we should make it an un-happy path in the UI

@paynejd Good thought. Should we tackle this issue when we get to the Form UX design initiative? Maybe a good short term solution would be to modify the label for the UUID option to say it's not recommended (for Mnemonics only, not for External IDs). 

QUESTION: Is it only Concept Mnemonics that we would not recommend using UUIDs, or are Mapping Mnemonics included too?

Example:
![image](https://user-images.githubusercontent.com/55999682/172624129-2a496c93-9b8c-4eb4-b98c-e52a08633baa.png)

**Comment by askanter** [comment]
Not specifically commenting on UUIDs for mapping IDs, but I would suggest that mapping IDs are not every viewed by humans. The mapped code system/codes are, but not the relationship between the concept and the codes. Same would apply to concept-concept maps, since the concept ID would be referenced, not the mapping ID.

Andy
Andrew S. Kanter, MD MPH FACMI FAMIA

Asst. Professor of Clinical Biomedical Informatics and Clinical Epidemiology
Columbia University

E: ***@***.***

**Comment by jamlung-ri** [comment]
The first round of this work is in good shape. Paul Adams is designing forms that should fix the rest of the UI-related issues in this ticket.
