### ISSUE TITLE
Implement ability to track bulk import process when requesting status

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#122]
Not urgent, but would be really helpful if the status request indicated how many records had been processed out of the total amount, either as a string or 2 numeric values. For example, something like this: "bulk_import_progress": "4 records processed out of 1,300".

**Comment by paynejd** [comment]
Being able to track the progress of a bulk import becomes more important as we experiment with larger import files and with queuing. It should be easy to "pre-process" the import JSON to determine how many resources are included (ie. the number of lines in the file that contain JSON). The total number of resources could be stored along with the task. The number of resources imported so far could also be stored with the task, and this would only need to be updated periodically (i.e. every 10-15 seconds). 

Finally, we may want to modify the "status" field:
* "PENDING" would mean that the import is queued -- do we also return position in the queue? (low priority if yes). Let's also return the user that requested the import and when the import was requested
* "PROCESSING" should be used to indicate that it is being actively imported -- this would include the total number of resources in the import, user that requested the import, when the import was requested, and how many resources have been imported so far
* "ERROR" -- something went wrong?
* or return JSON, report, or summary

Let's consider this ticket together with #108

**Comment by harpatel1** [comment]
@rkorytkowski Can you update on the status of this ticket ?

**Comment by aprilcurrier** [comment]
No work completed rolling over

**Comment by paynejd** [comment]
@rkorytkowski Can you connect with @snyaggarwal to determine how to implement this within oclapi v2? This is not urgent, but we just don't want to lose track of it. We do not need to implement this in oclapi v1

**Comment by paynejd** [comment]
Please refer to #108 for a related ticket about implementing this via response headers.

**Comment by paynejd** [comment]
#253 #259 #108 -- These all require changes in docker to function in oclapi2. @rkorytkowski is working on this

**Comment by harpatel1** [comment]
Need to have discussion with @rkorytkowski  and @snyaggarwal

**Comment by aprilcurrier** [comment]
@snyaggarwal  to update statuses. @rkorytkowski  to update docker. Code implementation is done in OCL API 1 and 2.

**Comment by snyaggarwal** [comment]
# Possible statuses and its meanings:

## Task state is unknown (assumed pending since you know the id).
PENDING = 'PENDING'
## Task was received by a worker.
RECEIVED = 'RECEIVED'
## Task was started by a worker.
STARTED = 'STARTED'
## Task succeeded
SUCCESS = 'SUCCESS'
## Task failed
FAILURE = 'FAILURE'
## Task was revoked.
REVOKED = 'REVOKED'
## Task is waiting for retry.
RETRY = 'RETRY'
IGNORED = 'IGNORED'
REJECTED = 'REJECTED'

## Set of states meaning the task result is ready (has been executed).
READY_STATES = [SUCCESS, FAILURE, REVOKED]
## Set of states meaning the task result is not ready (has not been executed).
UNREADY_STATES = [PENDING, RECEIVED, STARTED, RETRY]
## Set of states meaning the task returned an exception.
EXCEPTION_STATES = [RETRY, FAILURE, REVOKED]
## Set of exception states that should propagate exceptions to the user.
PROPAGATE_STATES = [FAILURE, REVOKED]
