### ISSUE TITLE
Implement Operations panel MVP in the TermBrowser

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1222]
This is the follow up to #1189 

Mockups and details here: 
[Achieving full SVCM support in the OCL TermBrowser Jan-2022](https://docs.google.com/presentation/d/1jv6BeFzwNbPDffHPPU0B3lDClGYt6ZO5rc_K2ORa7vc/edit?usp=sharing) (Specifically, see slides 16-19 were added)
[Framer Mockup for Operations Panel](https://framer.com/share/TermBrowser--onB59TV7OytQ2Urr6McM/FZ2ZjeV2Q)

**Comment by jamlung-ri** [comment]
Example CodeSystem $lookup and $validate-code operations to develop against:

Example $lookup operation: https://fhir.qa.openconceptlab.org/orgs/WHO-DDCC/CodeSystem/$lookup/?system=http://worldhealthorganization.github.io/ddcc/CodeSystem/DDCC-QR-Format-CodeSystem&code=image

Example $validate-code: https://fhir.qa.openconceptlab.org/orgs/WHO-DDCC/CodeSystem/$validate-code/?url=http://worldhealthorganization.github.io/ddcc/CodeSystem/DDCC-QR-Format-CodeSystem&code=image

**Comment by snyaggarwal** [comment]
From the deck:

- [ ] Available to admins only
- [ ] Support the two main CodeSystem operations ($lookup and $validate-code)
- [ ] Bonus is to add $cascade for the MVP too
- [ ] Input parameters initially:
  -  Operation
  -  System (owner + source + version)
  -  Code
- [ ] Constrained to the server you are currently looking at
- [ ] Want to start with Operations Panel on both OCL and HAPI connectors
- [ ] Assume that all connectors support the FHIR endpoints and start with global namespace only:
  - All servers: Support global namespace (because there is no owner namespace for FHIR)
  - TermBrowser may be more limited in the form fields that it can provide to help you select your Input Parameters
  - After the MVP: OCL Connector can also support owner namespace (in addition to global namespace), and can provide richer form fields to select your Input Parameters
- [ ] Add “Operations” Submenu under Concept details Actions (previously “Manage”): “Lookup” and “Validate Code” - this should work for any concept details (global search, source, etc.)
- [ ] Display the request URL that was generated
- [ ] Results are simple formatted JSON display
- [ ] Bonus: Can be opened in a new tab/modal window to view the JSON results in full screen

**Comment by jamlung-ri** [comment]
This is a great start! 

Running list of feedback for Operations Panel:

- [ ] When I scroll to the right, the text seems to go off of the black screen 
![image](https://user-images.githubusercontent.com/55999682/163192458-9ed9f290-2bb3-4def-8781-6bace5166b3e.png)

- [ ] The Execute button gets lost when the JSON list is long, so maybe that can be moved up above the Results list?
- [ ] When I try to open the Operations panel, the Download option above it has a tooltip that often overlaps. Maybe the options can be switched in that menu?
![image](https://user-images.githubusercontent.com/55999682/163194344-9767cd9a-f27d-408b-b843-53bba19c5e4f.png)

- [ ] I am unable to type in the CodeSystem field. This is needed if I am to test HAPI FHIR operations.

**Comment by paynejd** [comment]
The primary use case for operations within OCL is to have it pre-populate
fields based on a user's selection, or to allow a user to select a resource
in the operations panel with dynamic dropdowns, similar to how the Add
References tools work.

Like Joe is suggesting, it would be great to have a radio toggle that
replaces the dropdowns with text boxes that allow a user to directly type
in a canonical URL to manually test out an operation on a resource

**Comment by jamlung-ri** [comment]
One more feature: Add "Copy URL" button

**Comment by jamlung-ri** [comment]
Noticing an issue when doing operations with HAPI. I was unable to validate a code from there, and I realized it was because the Operations Panel is assuming that version=HEAD in HAPI, which is not the case. 

Incorrect request URL: https://hapi.fhir.org/baseR4/CodeSystem/$validate-code?code=HAPMAR&url=http://hl7.org/fhir/CodeSystem/Testing_10182019&version=HEAD

Corrected request URL (without version parameter): https://hapi.fhir.org/baseR4/CodeSystem/$validate-code?code=HAPMAR&url=http://hl7.org/fhir/CodeSystem/Testing_10182019

Screenshot if helpful: 
![image](https://user-images.githubusercontent.com/55999682/164230226-7341f63b-b93b-4fff-ba35-b6193c04dd3b.png)

**Comment by jamlung-ri** [comment]
One other thing that would be helpful (but not immediate) to fix would be the Version field being sensitive to the screen I am on. The Operations Panel seems to assume the HEAD version of a concept, even if I am looking at a specific version of a source. Screenshot: 
![image](https://user-images.githubusercontent.com/55999682/164232082-e95949a7-073a-4f47-a527-3bf1556f9bb1.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri both issues are fixed and deployed on QA

**Comment by jamlung-ri** [comment]
> One other thing that would be helpful (but not immediate) to fix would be the Version field being sensitive to the screen I am on. The Operations Panel seems to assume the HEAD version of a concept, even if I am looking at a specific version of a source. 

This is working great now! 

With the other issue, related to querying the HAPI server, it looks like it's still trying to add the Version parameter to the request. See this video for an example: https://www.loom.com/share/a1ff0e9a7daa4a3ba30da73601fbda8c

**Comment by snyaggarwal** [comment]
@jamlung-ri Fixed and deployed
