### ISSUE TITLE
List References for a concept when showing the concept in a collection

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1280]
For some concepts in a collection, there will be multiple references that cause the concept to appear in this expansion. We need to show those to the user somehow, so they know that the concept may be coming both from a direct reference AND a dynamic reference, for example.

This should appear in a new section in the concept details screen called "References" with a tooltip that says something like "This concept appears in this collection expansion as a result of these references."

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on QA/Staging

**Comment by jamlung-ri** [comment]
@snyaggarwal The section itself is looking good, but it looks like the References section is showing the reference's URI, rather than the Expression. I think users will want to see the Expression though. This would apply to both the Concepts and the Mappings displays. Are there any cases where this wouldn't work?
![image](https://user-images.githubusercontent.com/55999682/164017512-9a47ec9f-40a4-451d-86b2-12ffcf0bb8b7.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri Yes this is currently showing reference's URL.
In order to show the expression of references, will have to do following:
- Create an API to get references details from a concept/mapping:
  - `GET /orgs/MyOrg/collections/MyCollection/concepts/MyConcept/references/`, or
  - `GET /orgs/MyOrg/collections/MyCollection/concepts/MyConcept/?includeReferences=true` similar to `?includeMappings=true`
- Once one of the above is done, we can show expressions. What will be the onclick behaviour:
  - Take the user to result of expressions? -- that may or may not be same as what was evaluated
  - Take the user to reference details? -- same as right now
  - No OnClick?

**Comment by jamlung-ri** [comment]
>     * Create an API to get references details from a concept/mapping:
>       * `GET /orgs/MyOrg/collections/MyCollection/concepts/MyConcept/?includeReferences=true` similar to `?includeMappings=true`
This API looks a little better to me, but I don't really know if there are pros and cons to either one.


>     * Once one of the above is done, we can show expressions. What will be the onclick behaviour:
I don't know of a need to look through the result of the expression at this time, so let's keep it simple and just remove any on-click behavior for now. We can add more functionality in later if people request it, but I don't think it's necessary right now.

**Comment by snyaggarwal** [comment]
@jamlung-ri went ahead with `?includeReferences=true` and showing expressions with a chip to view details of reference. This is available on QA
