### ISSUE TITLE
[Reference] TermBrowser to allow expanded structure of Reference expression

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1289]
Currently, TermBrowser allows the addition of reference expressions in following ways:

  1. By global search 
  2. By drilling down the resources
  3. By adding an API expression

We should now allow adding the expanded structure of a reference from TermBrowser
Note: The API work was done as part of #1275

@jamlung-ri @paynejd Let's discuss some ideas for this.

**Comment by jamlung-ri** [comment]
Just wanted to throw this idea out before I forget - maybe we could base our ideas on a query builder like [this one](https://bestofreactjs.com/repo/ukrbublik-react-awesome-query-builder-react-miscellaneous)? We could even include a Preview feature so the user could get a glimpse of how their reference expression would expand.

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd first attempt on this should be available on QA now.

**Comment by jamlung-ri** [comment]
Really cool way you incorporated it! It feels good and powerful.

Some feedback:
* Can the "Include" button be a switch or something so that it's clear that it's either Include or Exclude?
* Is there a way to filter for Active concepts only? I know you can do it in the Expansions, but what about in the references?
* I notice that it always brings up the cascade prompt when submitting an expanded reference, which may be okay, but just wanted to check that this behavior is expected and makes sense.

**Comment by snyaggarwal** [comment]
@jamlung-ri Did 1 and 2.
3. We don't have an option to add active concepts/mappings in the new expanded structure, the old way can still work `/orgs/CIEL/sources/CIEL/?includeRetired=false`. We should discuss if want it in new structure and how the syntax should look, cc @paynejd 
4.  Ya! totally agree! Not sure how to manage that yet!

**Comment by jamlung-ri** [comment]
> @jamlung-ri Did 1 and 2. 

Verified that this looks good and works in QA!

**Comment by jamlung-ri** [comment]
> 3. We don't have an option to add active concepts/mappings in the new expanded structure, the old way can still work `/orgs/CIEL/sources/CIEL/?includeRetired=false`. We should discuss if want it in new structure and how the syntax should look, cc @paynejd

@paynejd Other than the point above, I think this ticket is in good shape to close out. Maybe we should simply implement Active or Retired as a filter, similar to how Datatype and Concept Class can be filtered?

Otherwise, I think #4 above can be handled when we get to the Form Improvement UI initiative.

**Comment by jamlung-ri** [comment]
Closing this ticket out. Next step here is to work on the UI for it, which will be addressed in [this document](https://docs.google.com/document/d/1W88DUB9NFn-Y4Br1vlNdV6DuDeh3skO1IO2HgdxUh6o/edit).
