### ISSUE TITLE
Mapping Issue - Concept Name not appearing

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1325]
When I create a mapping and then try to view the From concept, the mapping name does not seem to be appearing, even though the mapping resolves. See this [concept](https://app.qa.openconceptlab.org/#/users/ocladmin/sources/asdfasdf/concepts/6/) (plus screenshot): 
![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/ef385f45-38fc-41ce-afe2-041fff88456a)

This is also happening in Production - see [here](https://app.openconceptlab.org/#/orgs/OHRITechGroup/sources/OCT/concepts/assesedForPain/).

**Comment by paynejd** [comment]
In FHIR, mapping name is an explicit field that is stored with the mapping,
as opposed to something that is auto-populated based on the concept/code
that a mapping points to. This is the equivalent of how in FHIR, a Value
Set author can specify a "display" for a code directly in the ValueSet
compose statement.

There are 2 features to consider here for the UI:
1. A mapping author should be able to optionally auto-populate a name if a
target concept is defined in OCL
2. When listing a mapping and a target concept name is blank in the
mapping, the TermBrowser can try to lookup that concept in OCL and if it
finds it, display the name with different formatting (e.g. gray) to
indicate that it was looked up and not stored in the mapping

**Comment by jamlung-ri** [comment]
Oh nice, thanks Jon for the explanation. In this case, the second feature you mentioned would work well. If there's a mapping property for display name, then display that. If not, then try to lookup the name from the mapped concept and display that, probably with the gray or other formatting (plus maybe mouseover text to explain that this was looked up?).

@snyaggarwal Does this approach sound good to you?

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd 
- Associations are now loaded from $cascade operations (`?cascadeLevels=1` & `?cascadeLevels=1&reverse=true`)
- The "name" attribute is "target_concept_name" and can be an expensive field if not defined on Mapping.
- We dint add "target_concept_name" in Bundle Responses because in order to visualize $cascade we use the target resource that's part of the Bundle response (generally). This fails when the target concept is defined in some other Source (happening in this case).
- I have added "target_concept_name" in the Mapping response of the Bundle, which will return 
   - "Mapping.to_concept_name" (or "from_concept_name" in case of inverse/reverse) always
   - if "to_concept_name" is not specified then "to_concept.display_name" in cases where Mapping's parent and target concept's parent doesn't match.

**Comment by snyaggarwal** [comment]
@jamlung-ri Can we close this?

**Comment by jamlung-ri** [comment]
This is looking good to me!
