### ISSUE TITLE
Association section displays self-mappings twice

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1349]
The Associations section displays concepts twice when it's a self-mapping. 

![image](https://user-images.githubusercontent.com/55999682/175529642-b70bc67b-1751-4953-98b2-6a6e4fca0d66.png)

_Originally posted by @jamlung-ri in https://github.com/OpenConceptLab/ocl_issues/issues/1320#issuecomment-1165502546_

**Comment by paynejd** [comment]
@snyaggarwal @jamlung-ri Wasn't this already implemented?

**Comment by jamlung-ri** [comment]
It still seems to be occurring in QA 
![image](https://user-images.githubusercontent.com/55999682/194054041-a77bd03f-6914-4705-b1f9-274b6f4790bd.png)

**Comment by snyaggarwal** [comment]
@paynejd This is not yet done for associations listing. 
Handled in cascade visualisation though

**Comment by snyaggarwal** [comment]
Adding @paynejd's [comment](https://github.com/OpenConceptLab/ocl_issues/issues/1320#issuecomment-1274225657) from previous ticket

> Ideally, the TermBrowser would identify a self-map and display it only once
with a different icon. Instead of "-1" for inverse, maybe it would use an
infinity symbol "∞", a cricular arrow "⟳" or something similar? We would
definitely want to add a tooltip on that symbol to indicate that it is a
self-map.

**Comment by jamlung-ri** [comment]
This is looking good on QA. I was able to create a self-mapping on a concept and see the infinity symbol on it, and it only displays once.

**Comment by snyaggarwal** [comment]
this is deployed everywhere, closing this.
