### ISSUE TITLE
Blocker: Cannot remove References/Mappings from my collection

### ISSUE THREAD

**Issue by gracepotma** [OpenConceptLab/ocl_issues#1395]
Situation: I need to delete a mapping to a retired concept. This mapping (2554) got auto-imported into my collection, but the concept (162339) did **not**, because 162339 is retired. 
This is causing a blocking error in OpenMRS: "Cannot save mapping https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/mappings/2554/ [CAUSE]: Cannot create mapping to concept with URL https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/162339/, because the concept has not been imported". 

I thought I could get around this by removing the reference/mapping to the retired concept, in my collection at least. But when I select mapping 2554 and click "Remove Reference", I am blocked/stuck: 

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/67400059/198160189-6d43f346-07ad-4fd8-8b32-0017edb71064.png">

CC @jamlung-ri & @snyaggarwal

**Comment by gracepotma** [comment]
Note: For now I have unblocked us by adding the retired concept. But this feels pretty gross.

**Comment by jamlung-ri** [comment]
@gracepotma MAY BE URGENT: I was trying to see if I could replicate the error in [your collection](https://app.openconceptlab.org/#/orgs/openmrs/collections/CIELImmunizationContent/references), and accidentally removed the reference for that particular mapping from the References tab. Please let me know if you want me to undo that. That said, it did not remove the mapping itself from the collection since that mapping is there as a result of a cascaded reference. (See screenshot)

@snyaggarwal Are you able to look into the bug that Grace is showing? I am seeing the same thing - the [mapping](https://app.openconceptlab.org/#/orgs/openmrs/collections/CIELImmunizationContent/mappings/2554/) is there as a result of the cascaded reference from 984, and OCL is not showing the option to Exclude that mapping.

I also want to recognize that there is a chance that this has already been resolved in a previous bug fix, but it may not have been deployed to Production yet.

![image](https://user-images.githubusercontent.com/55999682/198326721-d725d13c-27ba-4428-855e-fa0ca5f41407.png)

**Comment by gracepotma** [comment]
Thanks @jamlung-ri. TBH I had to go to your OCL youtube channel and watch the References video again to remember the implications - I tend to imagine them as being equivalent to mappings but obvs that's not the case. 

We're safe for the immediate present because of versioning - I released a version yesterday before your accidental deletion. And I don't think it matters because as you said it's a reference to a _mapping, and that mapping is to a Retired concept which is very very unlikely to be updated so there's really no need to maintain a reference to that mapping, IMHO. And finally, I think if @snyaggarwal can unblock us at removing the mapping, then there's no need for the reference at all. Then I would just need to go in and remove the 162339 concept once and for all :) 

TBH It never even occurred to me to touch the References at all - they're still kind of a nebulous area for me so I (and the users I've watched) tend to only focus on the Concepts tab. The only reason I was looking at mappings at all is due to this error message we were getting about a mapping.

**Comment by paynejd** [comment]
This is probably addressed-- @snyaggarwal @jamlung-ri to test and confirm

**Comment by jamlung-ri** [comment]
I attempted to recreate this, and it seems fixes, as far as I can tell.

**Comment by snyaggarwal** [comment]
@jamlung-ri I think we can close this.
