### ISSUE TITLE
Preliminary analysis of Multilingual TermBrowser UI work

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1438]
We want to be able to support the 6 UN languages in the TermBrowser UI. While OCL support multi-lingual user content (like concept names/descriptions), it does not yet support translations for user interface text.

We also do not let user's take advantage of multi-user content in the TermBrowser. Some enhancements are required to modify API responses and the TermBrowser to present multilingual content for requests with a language preference other than English.

@snyaggarwal Do you have enough info to draft an approach/requirements for this?

**Comment by paynejd** [comment]
* Right-to-left language support - the 6 UN languages includes Arabic

**Comment by paynejd** [comment]
Let's start to capture early requirements here
cc @snyaggarwal @paulsonder

**Comment by paulsonder** [comment]
Some quick design considerations here...

- Typography - I think it would be preferable to create some mocks of the 6 languages in use to asses our use of Roboto. Noto Sans has some key differences by design that allow in particular for a more readable Arabic script without making text larger for certain languages or scripts (Arabic scripts generally render small than Latin).
- We should also think about how our UI works when we have multiple languages in the same component, in a Concept detail  page for example.
- Numbers and numerals shouldn't change direction (same for dates)
- Directional iconography generally does, such as arrows or a book, but others do not, so we should consider this. I already have an analysis of our icons in use, so can augment this list with some thoughts on RTL.
- Scroll bars would flip direction.

All in all, it would be worth working through this subject in design as well as on the front end to test out some of our components first.

CC @paynejd @snyaggarwal

**Comment by snyaggarwal** [comment]
### Tasks:

 - Extract out English language bundle from the current TermBrowser:
   - All static labels are to be extracted and kept in YAML/JSON file
   - TermBrowser to use keys from the language bundle 
   - React to inject language bundle file
- Language bundle storages -- probably on S3 - `ocl-language-bundle.<env>.<version>.<language>.yaml/json`
 - Customise TermBrowser with [rtlcss](https://rtlcss.com/)
   - for languages right to left, TB needs to flip everything horizontally and right-aligned. rtlcss can help in that to cover the basics and rest needs to be applied as overrides on rtlcss.
   - Left Menu and other components needs to be manually flipped to rtl
