### ISSUE TITLE
Sort Weight on Mappings

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1446]
- It will be a direct optional float field on Mapping -- `sort_weight`
- Sorting applies within a single map type for any individual "from" concept
- We need to be able to import & export a numeric sort weight
- Sorting is done by ascending sort weight (smaller number first)
- Need to support sort weights that are decimals (at least during import)

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd this is deployed on QA and Staging with following features:
- sort_weight is a float field on Mapping
- Can assign sort weight from TB while creating/updating Mapping
- Can import sort_weight from Bulk Importer via JSON/CSV (updated ocldev)
- Exports will have sort_weight
- `$cascade` and `/<concept>/mappings/` API will apply sorting on map_type + sort_weight in asc order

**Comment by snyaggarwal** [comment]
@paynejd @jamlung-ri Next to consider on this is Quick Add Mappings.

**Comment by jamlung-ri** [comment]
Things appear to be working well on this! I tested in this source, and I was able to Quick-Add mappings, then open the Mapping details to assign a numeric sort weight. I could see this sort weight in the API, in the source version export, and in the Mappings CSV download. 

I did NOT have any luck with the CSV bulk import of sort weight, however. Here is the [source](https://app.qa.openconceptlab.org/#/orgs/DemoOrg/sources/MyDemoSource/) and [the CSV](https://drive.google.com/file/d/1lmK0qDlDJU4Mth__gCeSkPkiON0c0I02/view?usp=sharing) I am trying out. @snyaggarwal Am I using the right attribute name (`sort_weight`) for the three mapping rows in that CSV?

It looks like the float might be limited to 5 decimals (at least in the TermBrowser), based on this error message I received. 
![image](https://user-images.githubusercontent.com/55999682/209141532-be840db2-c511-45b0-b634-430eeefe725a.png)


One little 'bug' that is not high priority: there have been a couple of instances where OCL seems to be changing the decimal number I input. For example, on [this mapping](https://api.qa.openconceptlab.org/users/ocladmin/sources/asdff/mappings/6/), I tried to assign the sort_weight of 0.875, but OCL registered it as 0.87495 in the API and in the Mappings CSV download. It took me a bit to realize that this was because I attempted to use my mouse's scroll wheel to scroll down on the form, which TermBrowser registered as me trying to decrease the number on the sort weight. The buttons to add or subtract on the right side of the field seem to be causing this. Can we remove the numeric scroll on this field in the mapping form on TermBrowser?
![image](https://user-images.githubusercontent.com/55999682/209142166-92995e33-3bb7-4885-993f-4e4b30a79782.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri Deployed on QA

**Comment by jamlung-ri** [comment]
> This is the default htlml5 number field. I have converted it to a normal text field and on submitting it will throw an error if the value is not numeric. This will also lifts the restriction on number of decimal places.

Thanks @snyaggarwal, this field now seems to be working better. The only slight change I think we need is the error text. It's currently "Please match the requested format." Maybe instead it should say "This must be a number, with decimals allowed." just to be more clear?

Otherwise, the only thing left is the CSV Bulk Import issue. Once that's working, then I think we'll be able to deploy and close this ticket in preparation for the TermBrowser UI change for sorting (which still needs to be designed).

**Comment by snyaggarwal** [comment]
@jamlung-ri Fixed the CSV issue, that should work well.
The error message is from the standard error message from html5/browsers. We can show helper text at the bottom of the field, may be a tooltip will help here.

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on QA

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd This is deployed everywhere

**Comment by jamlung-ri** [comment]
FYI I tested the CSV import and it seems to be working.

**Comment by jamlung-ri** [comment]
@snyaggarwal One issue to note in the UI: The sort weight of mappings seems to be interrupted if the target concept is not in OCL i.e. it has an orange link icon. See [this API result](https://api.qa.openconceptlab.org/orgs/DemoOrg/sources/MyDemoSource/concepts/Act/mappings/), which correctly has the "non-existant" concept first. But in the UI (see [here](https://app.qa.openconceptlab.org/#/orgs/DemoOrg/sources/MyDemoSource/concepts/Act/)), that concept is at the bottom of the list. Screenshot: 
![image](https://user-images.githubusercontent.com/55999682/210370188-be1e3250-5308-4f39-977a-4cc5052860ec.png)

**Comment by snyaggarwal** [comment]
@jamlung-ri Fixed, will be deploying on QA tomorrow morning.

**Comment by snyaggarwal** [comment]
@jamlung-ri Can this be closed?

**Comment by jamlung-ri** [comment]
Yeah, I think we're done here for now.
