### ISSUE TITLE
Missing concept name in mapping section

### ISSUE THREAD

**Issue by suruchee** [OpenConceptLab/ocl_issues#1463]
The mapping in the concept does not have a name under the Associations section https://app.openconceptlab.org/#/orgs/openmrs/collections/ANCDAK/?q=&isTable=true&isList=false&page=1&exactMatch=off 

<img width="1437" alt="Screenshot 2023-01-18 at 3 32 43 PM" src="https://user-images.githubusercontent.com/19512272/213190156-a891a689-ad3c-4017-b717-ec4c358804f8.png">

**Comment by jamlung-ri** [comment]
Thanks @suruchee! @snyaggarwal I took a look at this earlier but could not determine why the concept name was not appearing. Things looked fine to me in the mapping JSON from the API.

**Comment by paynejd** [comment]
See the mapping in the API here:
https://api.openconceptlab.org/orgs/openmrs/collections/ANCDAK/mappings/20/4166700/

to_concept_name is null, which explains why it is blank

It is optional to store the name inside a mapping, and it is possible to
define a custom name in the mapping, or to store any of a concept's
synonyms with the mapping.

If you wanted to store a name with the mapping, can you explain how you
created it so we can make sure that it worked as expected?

Second suggestion: If a target concept exists and there is no name stored
in the mapping, the TermBrowser should look up the target concept display
name and show it in the list, with different formatting (e.g. gray text
instead of black) and probably a mouse over explaining where the name came
from. Thoughts on this approach?

**Comment by jamlung-ri** [comment]
@paynejd Does the `to_concept_name_resolved` not get used in the Associations section? I figured OCL TermBrowser would try to use the `to_concept_name` attribute, and if one wasn't specified, then it would resort to `to_concept_name_resolved`. Maybe that's not the case though.

**Comment by suruchee** [comment]
@paynejd, thanks for looking into it. I created mapping from the source by Add Mapping option and filling out the form then adding to the collection. So, what should I do to display name? 
Also mappings in source do have names in it.
<img width="1359" alt="Screenshot 2023-01-18 at 8 29 18 PM" src="https://user-images.githubusercontent.com/19512272/213201604-0e416bad-05f1-4070-8c8c-a47ab7c98ddf.png">

**Comment by snyaggarwal** [comment]
@paynejd @suruchee Looks like the mapping is fine, but an issue with `$cascade` response. The mapping response (inside cascade bundle) is returning the target concept's resolved name (`to_concept.name`) only if it belongs to a different source than mapping. I am not sure why this condition was added. For now, I have removed it, which should fix this issue.

**Comment by suruchee** [comment]
Thanks @snyaggarwal for the quick fix, so when will I be able to get it in production? And do I need to do anything to get the names?

**Comment by snyaggarwal** [comment]
it should reach production soon, within a week. You dont have to do anything, the data is all there, just not showing in TB

**Comment by snyaggarwal** [comment]
it should reach production soon, within a week. You dont have to do anything, the data is all there, just not showing in TB

**Comment by snyaggarwal** [comment]
@suruchee This is deployed on production

**Comment by suruchee** [comment]
Thanks @snyaggarwal
