### ISSUE TITLE
"Add to Collection" bug for a particular concept - Backend data bug?

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1485]
When trying to add a particular concept to a collection, OCL seems to be unable to do it. It either says "0 References Added" or it can't resolve the reference in the collection. 

Video of the behavior:  https://images.zenhubusercontent.com/122384560/e7ce7718-d2a6-49c7-bf7b-b44778e24162/screenshare___2023_02_23_1_43_25_am.mp4

"Assessment" Concept that is causing trouble: https://app.openconceptlab.org/#/orgs/openmrs/sources/SOAPNoteCodes/concepts/SOAPAssessmentCustomCode/
Grace's collection that can't get the concept: https://app.openconceptlab.org/#/orgs/openmrs/collections/soapnote/HEAD/expansions/autoexpand-HEAD/concepts/
My collection where I also can't get the concept: https://app.openconceptlab.org/#/users/jamlung/collections/troubleshooting/ (notice the unresolved reference in the References tab)

I wonder if there is a bug with the concept's versions in the DB, because I notice that the concept version IDs seem to be doing something weird. Looking at the concept URL, the `version` field shows "2886604", but the version URL field shows "/orgs/openmrs/sources/SOAPNoteCodes/concepts/SOAPAssessmentCustomCode/2886605/". Both version IDs resolve in the API (see links below), but only one version appears when calling the concept versions URL.
* Unversioned concept URL: https://api.openconceptlab.org/orgs/openmrs/sources/SOAPNoteCodes/concepts/SOAPAssessmentCustomCode/
 * Concept versions URL: https://api.openconceptlab.org/orgs/openmrs/sources/SOAPNoteCodes/concepts/SOAPAssessmentCustomCode/versions/
* One versioned concept URL: https://api.openconceptlab.org/orgs/openmrs/sources/SOAPNoteCodes/concepts/SOAPAssessmentCustomCode/2886604/
* Other versioned concept URL: https://api.openconceptlab.org/orgs/openmrs/sources/SOAPNoteCodes/concepts/SOAPAssessmentCustomCode/2886605/

**Comment by snyaggarwal** [comment]
@jamlung-ri This is happening because source [openmrs/SOAPNoteCodes](https://app.openconceptlab.org/#/orgs/openmrs/sources/SOAPNoteCodes/versions) has a released version which doesn't include this "Assessment" Concept. Check the [concepts](https://app.openconceptlab.org/#/orgs/openmrs/sources/SOAPNoteCodes/1/) it has (2 out of 3 from HEAD).

Explanation:
 - When we add references with OpenMRS Cascade, it tries to resolve the system version using `$resolveReference` operation. 
 - in this case $resolveReference receives system as `/orgs/openmrs/sources/SOAPNoteCodes/` and resolves to the latst released version which is version [1](https://app.openconceptlab.org/#/orgs/openmrs/sources/SOAPNoteCodes/1/).
 - if version is specified in the request then it will resolve to that, and if version is not specified (which is this case) then it will resolve to latest released or HEAD (if latest released not available).
 
 So to fix this:
 - You either need to generate a new version of this Source which will have all the concepts from HEAD and mark it released, or
 - You unmark the current latest version (1) as unreleased.

**Comment by gracepotma** [comment]
Thank you so much Sunny, this is an extremely good-to-know reference case. I'll follow your steps as described. My bad, I'm so used to using pre-published content like CIEL that it hadn't even occurred to me to be careful about my own Source publishing.

**Comment by gracepotma** [comment]
Okay I created a new release of SOAPNoteCodes and un-released V1. Assessment and Subjective codes both successfully loaded / updated respectively into my SOAP Note Codes collection; **however**, the Objective code remains a trouble-maker: you can see in my collection [here](https://app.openconceptlab.org/#/orgs/openmrs/collections/soapnote/HEAD/expansions/autoexpand-HEAD/concepts/) that it is not properly updating to reflect the V2 source release [here](https://app.openconceptlab.org/#/orgs/openmrs/sources/SOAPNoteCodes/concepts/ObjectiveFindingsCustomCode/). I still cannot remove it from my collection either as the UI blocks me just like in the earlier video. 

Any suggestions? Should I just remove it from the Source and re-create it? I could do that I guess, this just makes me a little nervous about the dynamic reference workflows going forward. I have also tried removing the Reference in the collection and then re-adding the code; this also didn't work.

**Comment by snyaggarwal** [comment]
@gracepotma Looks like there is some issue with your collection, it has the `Objective` code but not linking to any reference. There was a reference in references for this which I deleted, but the concept still remained in your collection. I will try to fix this bug. In the meantime, can you create a new collection try to add these code there, I just tested with one of my collections with these codes and everything worked fine for me.

**Comment by snyaggarwal** [comment]
@gracepotma Your source and its versions are absolutely fine.

**Comment by gracepotma** [comment]
Thanks Sunny - I re-created the collection and that worked. I wonder how exactly I corrupted the original collection. Just glad that didn't happen to a bigger, more mission-critical collection 😬 

Thanks so much for your rapid help, both you and Joe <3

**Comment by snyaggarwal** [comment]
Yes, thats something to debug, will keep this ticket until I find more on this.

**Comment by gracepotma** [comment]
That's reassuring, thanks Sunny :)

**Comment by snyaggarwal** [comment]
This is fixed and deployed everywhere. Closing this.
