### ISSUE TITLE
303 response when POSTing to repository export is missing Location header 

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#150]
When POSTing to a repository export that already exists (i.e. it is already cached on AWS S3), OCL returns a 303. A 303 status code is typically accompanied with a `Location` header and clients will automatically redirect to the `Location` url. OCL does not include the Location header, so instead clients just respond with a 303 and stop the request without redirecting.

Since I think this is incorrect behavior, we have 2 options:
1. Add the Location header so that the client automatically redirects and downloads the export, however this introduces inconsistent behavior for the POST request, which can either respond with a status code or, if we implement this new functionality, with the entire export. So that leads to option 2...
2. Modify the response code to something more appropriate that indicates that the client should now follow up with a GET response in order to download the export

The first option brings the API into compliance with the documentation, but I'm not sure that it makes sense to redirect to and return the full export when the actual request was to generate an export. Maybe just returning a 303 with no Location attribute is the right answer then! What do you think?

**Comment by harpatel1** [comment]
I agree with your point that since the request is for generating the export and not actually downloading the file. We return 303 but not Location header which is also not correct way. I think for the POST request, we need to change the return code to 200 or something similar when export file already exists and then users can use GET to download the export file. Returning 303 with Location header seems appropriate for GET request I can't say same for POST. I think we need to take following action:
1. Update the POST status code for the case when export file already exists to 200 and we are returning 202/409 when file does not exists which make sense.
2. Update the Documentation
Let me know what are your thoughts.

**Comment by harpatel1** [comment]
@paynejd  and I discussed this and we came to conclusion that we are going to keep 303 response without Location header for POST request. I have updated the API documentation.
