### ISSUE TITLE
Unable to bulk import a .csv file with bulk importer 

### ISSUE THREAD

**Issue by laurekpea** [OpenConceptLab/ocl_issues#1504]
We are following the same steps as usual, same formatting but since yesterday, after hitting the upload button the 'Import successfully queued ' pop up message shows up and then nothing imports. 
The 'existing imports' tab says 'No Tasks Found' and we can see after clicking on the filter icon that 'Started(0)' status keeps loading. The situation remains blocked at this step and we don't see any error message.
We tried around 1:30pm and 4:30pm on March 7th and around 10am today.

**Comment by paynejd** [comment]
@laurekpea Your bulk imports should have now been processed. Some tasks earlier in the queue got stuck due to out of memory issues that have been resolved, which backed processing up.

Also, @snyaggarwal created a new issue to make sure that pending processes like this appear in the queue in the TermBrowser so that you have more information on what's going on. See #1507

Let us know how things look on your end.

**Comment by laurekpea** [comment]
Thanks @snyaggarwal and @paynejd, it looks as expected on my end. Looking forward to seeing the TB update.

**Comment by paynejd** [comment]
Great to hear @laurekpea! Will close this out then since progress is being tracked in other tickets...
