### ISSUE TITLE
Importing Sort Order from PIH Dictionary

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1525]
To help onboard PIH to OCL TermBrowser, we need to make sure that the existing sort orders in the PIH dictionary can be reflected in OCL.

Ellen Ball will add some more details here to help us get started. Let's start by understanding the requirements, then we can diagnose any existing gaps in OCL that might need addressing.

**Comment by lnball** [comment]
Sort order (weight) for concept answers and set members must be imported with the PIH dictionary into OCL.

Sort order is used by OpenMRS for data entry (htmlforms and custom lab modules) so that answers appear is a clear order (+++, ++, +, none) or hematogram with the results entry matching the lab equipment output paper.

This is from the [ocl staging server](https://app.staging.openconceptlab.org/#/orgs/PIH/sources/PIH/concepts/11711/) where the order is random:
![image](https://user-images.githubusercontent.com/1164849/226996207-0e108b93-14b3-49eb-b04d-09eb8f85181a.png)

**Comment by bmamlin** [comment]
I've [updated the ocl_omrs script](https://github.com/OpenConceptLab/ocl_omrs/commit/15c377d8bd0b79a4e1fa6c03063a1ed28fe0ce46) to move `sort_weight` from an extra to a first class citizen for imports. Initial testing looks good. I'll "weight" until a successfully import the next version of CIEL with this change before closing this ticket.

NOTE: we'll also need to make a ticket for the OCL module to look for the _native_ `sort_weight` property within exports before looking at extra properties and favor it over a "sort_weight" extra property (i.e., keep using "sort_weight" extra property for backwards compatibility, but  use the native `sort_weight` should both exist for a mapping). Over time, the number of mappings with "sort_weight" as an extra property will dwindle and we can deprecate & remove its use within extras from the module.

**Comment by lnball** [comment]
Thanks @bmamlin .  

FYI @mseaton

**Comment by paynejd** [comment]
@jamlung-ri Is this ticket done?
