### ISSUE TITLE
Sign-in/out with OCL Chat not carrying over to TermBrowser (and vice-versa)

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1582]
- Starting point: Signed out in both TermBrowser and OCL Chat
- Signed in as "jon" via the TermBrowser (which worked as expected), then went over to OCL Chat, and I'm still not signed in (including after hard refresh)
- In OCL Chat, I then clicked on "Sign In" and it automatically signed me in as "jon" without reentering my credentials
- Then I Signed Out in the TermBrowser (which again worked as expected) -- I stayed signed out after hitting refresh
- I then refreshed OCL Chat, but I remained signed in -- just to be sure, I tested this by doing several things that require that you are still signed in (like requesting an export of all of my personal data and activity)
- I then went back to the TermBrowser and clicked Sign In -- SSO sign in page appeared (meaning I was no longer signed as far as KeyCloak knew, but OCL Chat still thought I was) -- I then signed as a different user "datim-admin", which worked as expected in the TermBrowser
- I then went back to OCL Chat, hit refresh, and I'm still signed in to OCL Chat as "jon"

**Comment by paynejd** [comment]
Hey @rkorytkowski @snyaggarwal - can we prioritize this?

In brief, if I do an SSO sign-in or sign-out in OCL Chat, it does not carry over to TermBrowser, and vice-versa, which basically means that we do not have SSO.

**Comment by rkorytkowski** [comment]
@paynejd it's by design. SSO works this way. Once authenticated via SSO individual apps are responsible for maintaining the session and not hitting SSO with each request, thus they do not know if logout happened. It would be too much overhead to check SSO for each request within an app.

There's an addition to the OpenID protocol to handle single log out, which is supported by Keycloak (backchannel logout), which we could implement for TermBrowser, but as far as I can see it's not implemented for discourse. Nothing stops us from contributing upstream ;) In such a case an app provides a logout endpoint that can be hit by SSO if the user requested to be logged out.

Auto-login for individual apps can also be achieved, but it requires changes in code. Basically TermBrowser needs to try to authenticate in the background without any user action and ignore if it is not already authenticated with SSO. Again it's not available out of the box in discourse.

**Comment by snyaggarwal** [comment]
I will be looking into TB switching log-in/out based on discourse state changes

**Comment by rkorytkowski** [comment]
Just a note that from the perspective of the workflows described by Jon, the global logout is more crucial.

**Comment by rkorytkowski** [comment]
Here's an example implementation in Java that we should replicate https://developers.redhat.com/articles/2022/12/07/how-implement-single-sign-out-keycloak-spring-boot#back_channel_vs__front_channel_logout

**Comment by paynejd** [comment]
Closing this out as this will behave quite differently with the upcoming OCLv3 tools. Will create a new ticket if this is relevant then.
