### ISSUE TITLE
Adding concepts to a collection fails

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1602]
Laure at MSF showed us that when trying to add her concept into a collection using `Transform Static References = true`, a strange error occurs. OCL doesn't show any references added (see screenshot). I tried this again using `Transform Static References = false`, the reference does add but it remains unresolved. 

This is occurring on Production. 
Link to Laure's Concept: https://app.openconceptlab.org/#/orgs/MSFOCP/sources/MSFOCP/concepts/3080986/ and https://api.openconceptlab.org/orgs/MSFOCP/sources/MSFOCP/concepts/3080986/
Link to my troubleshooting collection with unresolved references: https://app.openconceptlab.org/#/users/jamlung/collections/MSF_test/references

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/12e98d7b-d918-4b45-8327-fccb278d2541)

**Comment by snyaggarwal** [comment]
@jamlung-ri This is a retired concept and also MSFOCP/MSFOCP resolves to V1 (latest released) version which doesn't have this concept. Version V1 created on 06/23/2023  and concept [3080986](https://app.openconceptlab.org/#/orgs/MSFOCP/sources/MSFOCP/concepts/3080986/) created on 06/28/2023
So in order to include this concept, you will have to use version=V1 and includeRetired=true

**Comment by jamlung-ri** [comment]
Laure reported that her latest attempt at this worked, so I am closing this for now.
