### ISSUE TITLE
Form / Edit user profile

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1617]

**Comment by jamlung-ri** [comment]
Questions to address (in separate tickets):
* Language: Should that be preferred locale? Need to think about requirements.
* Search preferences: Need requirements for this
* "Manage custom attributes": Should we show this somewhere in TB?

**Comment by jamlung-ri** [comment]
There are a couple of outstanding comments on the [design](https://zpl.io/Zq0xA9l) for @paulsonder, but this is mostly in good shape to begin development.

Some gaps to make sure we don't miss in development:
- Change avatar
- Change password
- Validate website URL (there's no validation currently)
- After editing profile, automatically refresh the user profile page

**Comment by jamlung-ri** [comment]
@paulsonder Please give the go-ahead if you feel that this is ready to go, and we can pass it to Sunny

**Comment by paulsonder** [comment]
@jamlung-ri 

Could you clarify the **Validate URL** requirement for me please?

Other than that I think we're good to move into development.

**Comment by paynejd** [comment]
Currently the form field accepts any value e.g. "dd". It should only allow
actual URLs

**Comment by jamlung-ri** [comment]
And that might be something that Sunny will handle as part of the components, not necessarily something that the design needs to have perfected. I think we can go ahead and put this into Development.

**Comment by paulsonder** [comment]
I updated the design to show we intend to use an [MUI Adorned Text Field](https://mui.com/material-ui/react-text-field/#input-adornments) here.

Thanks @jamlung-ri @paynejd

**Comment by snyaggarwal** [comment]
Couple of things here:
1. @paulsonder @jamlung-ri I think we should we have "Cancel" button in edit profile to go back to prev page, what do you guys think?
2. @paynejd we don't have `text` field in `User` model, (its only in `Org`) to save about info, should we add it there?
3. @paynejd For User's custom attributes, we do have this field but never used it. Should we make it searchable also?

**Comment by paulsonder** [comment]
Good catch re: the button @snyaggarwal - added to the design

**Comment by snyaggarwal** [comment]
@paulsonder Can you also update design with an option to remove a custom attribute

**Comment by snyaggarwal** [comment]
@paulsonder @jamlung-ri this is mostly done and available on QA.
Pending things:
1. Option to remove a custom attributes -- @paulsonder need this in designs
2. About for a user -- @paynejd we don't have `text` field in user, should we add this?

**Comment by jamlung-ri** [comment]
@snyaggarwal It's looking pretty good!

- [ ]  Can you make the left side (which has organizations and Edit Profile and all that) so that the Organizations section trims down if space runs low? I reduced the window size and lost my Edit Profile and Copy API Token buttons. See this gif for example:
![User Page Resize](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/0dac4600-42b3-4c2f-a950-8cf3df8c4102)

**Comment by snyaggarwal** [comment]
- Email Address is right now not editable. We can talk about it if we want to enable it via KeyCloak.
 - Made it scrollable

**Comment by paulsonder** [comment]
@snyaggarwal The edit user form has a pattern for removing a custom attribute.

**Comment by snyaggarwal** [comment]
> @snyaggarwal The edit user form has a pattern for removing a custom attribute.

@paulsonder Not sure if I understood this

**Comment by paulsonder** [comment]
Sorry @snyaggarwal - this was in reference to a request above to add a way to remove a custom attribute. You can see the updated design [here](https://zpl.io/Zq0xA9l).

**Comment by jamlung-ri** [comment]
Outstanding to-dos for this ticket:

- [ ] Discuss whether or not email address should be editable
- [ ] (Sunny's question above) About for a user -- @paynejd we don't have text field in user, should we add this?
- [ ] (Sunny's question above) @paynejd For User's custom attributes, we do have this field but never used it. Should we make it searchable also?

Otherwise, I think this form is in great shape. Let's see if we can knock out these discussion questions before closing out though.

**Comment by paynejd** [comment]
I would support adding a brief Bio for a user, similar to GitHub -- I think we want to design it so that these tend to be a 1-sentence headline rather than a paragraph:
<img width="407" alt="image" src="https://github.com/user-attachments/assets/0e08d2be-da3a-4719-8e15-048242ead70b">

User custom attributes are not really used - I wouldn't implement this in TBv3 at this time (and maybe never)

**Comment by jamlung-ri** [comment]
We decided in the Dev call today that Bio can be added to the User API. We do not need to build out custom attributes for User for now.

**Comment by snyaggarwal** [comment]
@paulsonder @jamlung-ri This was done and deployed. Please check and close if everything looks good.

**Comment by paulsonder** [comment]
<img width="763" alt="Screenshot 2024-07-30 at 11 20 33" src="https://github.com/user-attachments/assets/9514d51f-4f0c-4da4-9c10-642a60b09862">

@snyaggarwal Generally looking good. You'll notice in 'Name and description' that there's a defect with the URL text. Could this line be 3 columns and contained in the card? The fields below don't need to be, as per design.

I wonder if we should also constrain the cards width? In the design they're set at 750px.

@jamlung-ri I think it might make sense to have the 'Edit User' form as an option in 'Settings' - the CTA on the profile page can go there, as we currently only have the Canonical tool. What do you think?

**Comment by snyaggarwal** [comment]
@paulsonder Fixed the URL wrap. I have kept 85% of the width of the page and min width as 750px for now. Let me know if that works.

**Comment by snyaggarwal** [comment]
@jamlung-ri @paulsonder Please close this issue if everything looks good
