### ISSUE TITLE
Profile / User

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1627]

**Comment by jamlung-ri** [comment]
User stories and requirements:

Object +   CTA | User   Story | Requirements
-- | -- | --
User: Create Account | Create OCL account as an anonymous user | Single   Sign-on; takes user to Dashboard upon login unless on another OCL org, user,   or repo page already
User: Follow | See   events from this user (e.g. new repo/release) on my dashboard | See #1800 for recent activity   examples; show user events e.g. profile detail changes, creation or version   release of a repo, joined an organization, etc.; View events from followed   user on your Dashboard
User: View Follows/Bookmarks | View   the orgs and users that I follow so I can see what activity they have done   recently | List followed orgs and users in   a single list; navigate to a particular org or user from this list; manage   followed orgs/users e.g. unfollow; view and manage bookmarked repos (which   show their owner and canonical URL)
User: Copy Token | I   want to copy my own API token to my clipboard so that I can use it in other   applications | (Only from Dashboard/Profile of   the logged in user) Copy API token to clipboard
User: View | View   any user's profile so that I can learn more about them | See #1800
User: Search | Search   for a specific user on OCL so that I can find more information about them | Support sorting and filtering by   OCL attributes; repo list with card and table views; display username,   icon/profile picture, Company, joined date, etc.
User: Search | (Nice   to have) Search for content within the context of the user so that I can   discover what they work on | Search for repos (using repo   search object) in context of user (i.e. content owned by the user or owned by   an organization in which the user is a member)

**Comment by paulsonder** [comment]
@jamlung-ri I've added designs to the Object + CTA column. Please let me know here if anything is missing or unclear and I can clarify with additional notes.

**Comment by paulsonder** [comment]
There's also an example [here ](https://zpl.io/kKDrLeG) of when a user views another user, note the change to the CTA's...

**Comment by jamlung-ri** [comment]
One action item is to document the different feeds that we are using as part of Org Overview, User Profile, and Dashboard. Let's be clear about what goes in those and the differences between them. @jamlung-ri to do this

**Comment by paulsonder** [comment]
> Member

We could maybe have some in-person time with @snyaggarwal scoping this from an OOUX perspective.

**Comment by jamlung-ri** [comment]
We had some time to talk through this on the OCL Design Call today. Here's the Miro where we're compiling things: https://miro.com/app/board/uXjVK5g8WOU=/

**Comment by jamlung-ri** [comment]
Remaining things to be done before sending this to Dev:

- [ ] Address comments in the [User design](https://zpl.io/kKDrLeG)
- [ ] Finalize Feeds

**Comment by snyaggarwal** [comment]
@paulsonder @jamlung-ri Most of the things, other than events/feeds, are deployed. Can you please provide feedback

**Comment by paulsonder** [comment]
Hey @snyaggarwal 

Looking great! Into the finer details here, but some feedback on the UI.

- [ ] The name uses the Small Headline type style (24px) and is **Bold**.
- [ ] The User meta info, e.g. Location, Website etc should use Body Small.
- [ ] I'm going to document how we should display an Org that doesn't upload an Avatar a separate ticket in here: #1905 , but looks fine for now.
- [ ] The icon for Canonical URLs is different to the one I'm using - you can grab it from [here](https://zpl.io/JQEZrOr).
- [ ] I also updated the position of the Follow / Unfollow.

**Comment by snyaggarwal** [comment]
@paulsonder This is updated

**Comment by paulsonder** [comment]
@snyaggarwal The text changes (point 1 and 2) don't seem to be applied in QA?

**Comment by snyaggarwal** [comment]
@paulsonder Sorry forgot to deploy. It should be there in next 5 minutes

**Comment by jamlung-ri** [comment]
@snyaggarwal @paulsonder One small change: Should there be a "view less" for the overflow of followers? I expanded my Following icons to view more but couldn't view less unless I refresh the page. It might not matter, just one potential quick thing.

Otherwise this works great!

**Comment by snyaggarwal** [comment]
@jamlung-ri @paulsonder Added this

**Comment by jamlung-ri** [comment]
Awesome, this is great now. The only things left to implement on this page is the Recent Activity Feed and the Recently Updated Repositories ([design link](https://zpl.io/kKDrLeG)). @snyaggarwal Is this ready to move forward? Also please let us know if a new ticket is needed.

**Comment by snyaggarwal** [comment]
Closing this ticket. Lets create specific tickets for feedbacks and bugs.
