### ISSUE TITLE
Unexpected behavior - Add to Collection Bug?

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1643]
See video: https://www.loom.com/share/f31ecc2aff1f4815938741f7ed0f4e8e

In short, I can't add a [concept](https://app.openconceptlab.org/#/orgs/OHRITechGroup/sources/OCT/concepts/3309716/) into a [collection](https://app.openconceptlab.org/#/users/jamlung/collections/test1/) with OpenMRS Validation Schema enabled because a previous version of the concept has the same name as the CIEL concept in my collection.

**Comment by snyaggarwal** [comment]
Hey @jamlung-ri this is happening because [Concept:3309716](https://app.openconceptlab.org/#/orgs/OHRITechGroup/sources/OCT/concepts/3309716/) has an [old version](https://app.openconceptlab.org/#/orgs/OHRITechGroup/sources/OCT/concepts/3309716/3309718/) which has the same name as CIEL's concept, and this old version is in the [OCT's latest released version](https://app.openconceptlab.org/#/orgs/OHRITechGroup/sources/OCT/versions/).

You will have to create a new released version of OCT.

**Comment by jamlung-ri** [comment]
Thanks @snyaggarwal! Closing this out for now but will reopen if more issues arise.
