### ISSUE TITLE
Index Term name type not accepted with OpenMRS Validation Schema

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1709]
When adding a name to a concept in a source with the OpenMRS Validation Schema, I cannot add a name with type "Index-Term", even when using the name type in OCL's Form. The issue here is likely in the validation schema, but it could also be an issue in the UI form. I get the error when trying to submit the concept details below in [this source](https://app.staging.openconceptlab.org/#/users/jamlung/sources/openmrstest/).

<img width="1737" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemM1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ce90b2e7daa3670aef731369b0a9527bf98d118/image.png" alt="image.png" />

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFE1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50622280354ca7b9cc1671c5f50d8b3592ed1b6b/Recording%202023-12-06%20092949.mp4)

**Comment by bmamlin** [comment]
It might be because the [code contains "Index Term"](https://github.com/OpenConceptLab/oclapi2/blob/master/core/concepts/constants.py#L9) (with **space**), although the [actual ID of the name type in OCL is "Index-Term"](https://api.staging.openconceptlab.org/orgs/OCL/sources/NameTypes/concepts/Index-Term/) (with **hyphen**).

**Comment by snyaggarwal** [comment]
@jamlung-ri Fix is deployed on QA

**Comment by jamlung-ri** [comment]
This is fixed on QA! Ready to deploy

**Comment by snyaggarwal** [comment]
@jamlung-ri this is deployed on Prod
