### ISSUE TITLE
Repo version in search results

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1725]
### User story 1:

**As a:** Dictionary manager
**I want:** Understand the version of a Source that a Concept included in my Collection (Dictionary) is from
**So that:** I can simply check if all the content is using the correct or most recent version.

**Comment by paulsonder** [comment]
Updated UI can be found [here](https://zpl.io/jpjk48W).

**Comment by snyaggarwal** [comment]
@paulsonder this is deployed on QA

**Comment by jamlung-ri** [comment]
Looking good on the Concept Search Results! @paulsonder Do you also expect that this would go in the Repo search results page too, or is that a different ticket?

**Comment by jamlung-ri** [comment]
@paulsonder I think it'd be something like:

As a: Terminology Consumer or Dictionary Manager
I want: View the latest version of a repo that has been released (plus the date of release, ideally)
So that: I can quickly view if the content is "active" i.e. recently updated and decide if this is still being curated
