### ISSUE TITLE
My repositories

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1755]

**Comment by jamlung-ri** [comment]
Design links:
- [My Repos list](https://zpl.io/ggeQBvM)
- [My Repos with Pinned repos](https://zpl.io/jpj5R4r)
- [Create New repo](https://zpl.io/9N4wEZB) (currently should only include "Blank" repo until Repo Types are ready in #1695)

**Comment by snyaggarwal** [comment]
This is deployed on QA

**Comment by jamlung-ri** [comment]
Looking pretty good! The Owner should be added as a table column though, if possible. This is related to the discussion in [this ticket](https://github.com/OpenConceptLab/ocl_issues/issues/1756#issuecomment-1938638695).

Do you have a design for pinning an Org too? I didn't know we could do that, but I pinned an org on [my page](https://app.qa.openconceptlab.org/#/users/jamlung/collections/).

Specific feedback below:

- [ ] I'm noticing that the display for the pinned repos is a bit off. They're showing the pin ID, rather than the ID for the repo (e.g. "13" instead of "test-collection". 

- [ ] I also notice that the description shows only if the repo has a description. We might need to think about what gets displayed here in case of blank fields e.g. "description if not blank, then full name if not blank, then... nothing?" 

![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/73d33b46-bc70-453d-bc59-8a95360b6343)

**Comment by snyaggarwal** [comment]
@jamlung-ri Ya fixed the first one to show resource name or ID.
Second one, we do try to show description or full name, if both are empty then we show nothing

**Comment by jamlung-ri** [comment]
Great, with those issues fixed, I am feeling pretty good about this page. 

We did have a discussion earlier today about the fine line between My Repositories and the repos on the User Profile page. We should think about GitHub's way of doing this, and it might lead to changes either in this design or in the User Profile design #1756

**Comment by jamlung-ri** [comment]
Yeah let's close it, with the following tickets as next steps:
* My Repositories - Card View
* My Repositories - Create/Update
