### ISSUE TITLE
Org Home View Round 1

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1757]

**Comment by jamlung-ri** [comment]
One design for this is here: https://zpl.io/5NZJeG8

**Comment by snyaggarwal** [comment]
@jamlung-ri When there is no About entry and no bookmarks then the overview section remains empty. We need to think about this

**Comment by jamlung-ri** [comment]
Good start! A couple of things I'm noticing:

- [ ] The design shows two statistics that look like a sum of numbers that come from multiple repo summary APIs: "# Novel Concepts", and "# Versions published". I can envision how each of them are calculated, but does this seem technically feasible?
- [ ] "Most published content" which shows the top 3 most common concept classes seems useful, but again, it comes from a sum of repo summaries.
- [ ] My browser is showing unusual spacing or alignment for Members on the [WHO DDCC Org](https://app.v3.qa.openconceptlab.org/#/orgs/WHO-DDCC/): 
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/f6a114cd-cad0-4347-892d-9f94445dd6d4)


> @jamlung-ri When there is no About entry and no bookmarks then the overview section remains empty. We need to think about this

Good point, the current behavior shows something like this for an empty org: 
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/731a80f6-8e71-4bf1-b55b-3b9614b9cced)

**Comment by snyaggarwal** [comment]
@jamlung-ri Let's add this for discussion. This needs to be an API behavior. And I feel there should be a summary API for an Org.

**Comment by jamlung-ri** [comment]
@paulsonder As long as that fits pretty well with the About section, then I think that seems like a good idea to combine the About and Repos sections. GitHub does a similar thing and it feels good, even if there is no About text.

**Comment by paulsonder** [comment]
Hi @snyaggarwal and @jamlung-ri 

I've made some updates to the designs for this page.

The left side of the Org Overview now includes possibility to include the following:

1. **Pinned** repositories
2. An **About Us** section
3. **Featured repositories** - These are in card view. These could be 'Most recently updated' repo's unless an owner chooses to specify repo's to feature here?

I left the **Overview** and **Repositories** tabs but renamed the latter to **All Repositories** so that a user may view all repo's.

Update designs **[here](https://zpl.io/DpGd5Kr)**.

**Comment by jamlung-ri** [comment]
Thanks @paulsonder! A couple of thoughts:

1. We might want to just think about the difference between Pinning and Featuring a repository. I'm having a little trouble differentiating other than the idea of "Pinned Repos are slightly more highlighted than Featured Repos"
2. Can you put together a design for a brand new organization that was just created with only the absolute minimum info? Meaning, there would be no pinned repos, no About text, and no Features Repositories. If we can get this to look okay, then I think we're in good shape. Including GitHub's Blank repo page here since it's a cool example with immediate calls to action: 
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/cf94ad79-ce83-4d29-8504-464dce4373b0)

**Comment by jamlung-ri** [comment]
@snyaggarwal @paulsonder I think this ticket is pretty close to being able to close out as a Round 1 ticket, and we can put the remaining work in a follow up ticket. I'll go ahead and create a new ticket and link it here. @paulsonder Can you close this out if you agree?
