### ISSUE TITLE
New Cascade option - Transform to dynamic references

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1824]
Users are encountering an issue where they cannot add to an OpenMRS-validated collection because the validation schema won't allow duplicate fully-specified names (see #1795 for an example). A common example is where a user tries to add a labset with many cascaded concepts e.g. CIEL's [161451 Stool test](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/161451/), which has multiple overlapping "children" like Positive or Negative. If even a single concept is duplicative when adding that dynamic reference to the collection, the whole dynamic reference gets rejected by OCL (see error message below). The only option a user has is to add lots of static references, which makes updating the collection difficult.

I propose that there needs to be a new option in the Add Reference to Collection dialog, which is "Transform to dynamic references". This should be an alternative option to "Transform to static references" that OpenMRS users can start using. This might be a new cascade parameter in the API. It would return the same results as the "Transform to static references" option, except for the resource versions on the end of each transformed reference.

![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/ff1985c5-d644-4a43-82aa-9952e2643585)

Note that v3 need a better approach to this e.g. OCL returns a list of concepts that couldn't be added because of validation issues, even if they were added using a single dynamic cascaded reference.

Example error message
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/1458cde0-cdc6-4c23-9cfb-4d7c003f3917)

**Comment by bmamlin** [comment]
For OpenMRS dictionary management, ideally all references would be version-less unless someone went out of their way to say, in an exceptional circumstance, "I need to freeze this specific reference to an 'old' version of this concept."

When adding a concept to a collection, it would help if (like we did for cloning into sources) we could use SAME-AS mappings for equivalency – i.e., if there is a SAME-AS mapping to a concept being added to the collection, the concept itself is skipped (children would still be processed). For example, if concepts for "Positive" and "Negative" exist in a collection and are mapped to CIEL's equivalent concepts, then adding CIEL's "Stool test" concept would add the "Stool test" concept & its mappings, but would skip adding CIEL's "Positive" or "Negative" concepts (just as if these concepts already existed in the collection).

**Comment by jamlung-ri** [comment]
@bmamlin These are really good points, and I think this fits either into a sort of "smart cascade" or somewhere else in the collection management process. I would imagine that the bottom image is the ideal option, but not sure.

One important thing to note is that I think this likely ends up creating new mappings; if so, we come back to the Linked Sources piece where OCL would need to know where to put any new mappings that get created in this process.

OCL currently checks two things - is the newly added reference a duplicate of an existing reference in that collection, and does the reference result have any conflicts with the collection's validation schema? These both check for overlapping/duplicative content, but they aren't sensitive to mappings denoting equivalence. If we were going the "smart cascade" route, I think the general spirit of it would be this: In addition to the two checks above, mappings for concepts in the collection can also be checked to see if an "equivalent" concept exists. Not only would OCL be aware of that duplication, but it also could reconcile the differences by doing some intelligent remapping, much like the $clone operation does. 

Example workflow:
1. User adds Stool test to their collection (using a smart cascade with OpenMRS flavor)
2. OCL evaluates the cascade to return a list of concepts/mappings to tentatively add to the collection
3. OCL checks that list against existing concepts/mappings in the collection to ask the following:
      1. For each newly added concept, does it already exist in the collection? 
             1. If yes, reference might be added if not duplicative, but the collection's content will stay the same.
             2. If no, check next step before adding reference. 
      2. Do any concepts in the collection have a corresponding SAME-AS mapping to a newly added concept?
             1. If yes, this is the complex step that would not add a reference to the mapped concept, but instead create a brand new mapping (e.g. between CIEL's Stool Test and PIH's answer concept).
             2. If no, add the reference as per usual.
      
One other note though - I feel like this requires its own ticket. I don't think we can resolve this quickly, and Grace needs this fix ASAP, which is what this ticket intends to cover.

**Comment by paynejd** [comment]
First off- the references are already "dynamic", so "transform to dynamic" doesn't make sense. "Transform to static" takes the result of expanding intensional references and replaces those dynamic references with static references (extensional+versioned).

The "transform to static" option was implemented in the UI only to support desired behavior for OpenMRS dictionary managers -- no one else uses this. I think the OpenMRS community now would prefer that "transform to static" actually behaved as "transform to extensional" -- meaning, they would point to individual resources, but without the resource version.

This is great, because it will simplify dictionary maintenance and is in line with the best practice of controlling versions in the expansion instead of in the reference.

My thought is that we simply change the existing "transform to static" checkbox to work according to best practice. This might still require a new `transform` option in the API (e.g. `transform=exstensional`?)

Second- @bmamlin brings up really important points, and I agree with @jamlung-ri that this should be part of "v3 smart cascade/repo management" behavior.

Can we have a quick discussion on the dev call tomorrow to make a decision on this?

**Comment by jamlung-ri** [comment]
Yeah this sounds great to me! Let's queue it up for tomorrow.

**Comment by jamlung-ri** [comment]
New tooltip text that will be next to "Transform to extensional references":

> Using this checkbox will instruct OCL to create separate references for each individual concept or mapping (i.e. "extensional" or "one-to-one" references). 
> 
> Uncheck this box to instruct OCL to create fewer references that can represent multiple concepts and mappings  (i.e. "intentional" or "one-to-many" references).

**Comment by paynejd** [comment]
FYI @bmamlin confirmed in Slack that this is the approach to go with

@snyaggarwal Please go ahead with the "transform to extensional" approach

**Comment by snyaggarwal** [comment]
@jamlung-ri This is deployed on QA and Staging.

**Comment by jamlung-ri** [comment]
This is working as I'm expecting so far! I asked @bmamlin to see if we should do any more complex testing, but I think this is pretty close to ready to deploy to Prod.

**Comment by bmamlin** [comment]
I tested behavior on staging and it looks good. #1825 will help too.

This should make management of CIEL collections better for now. In the cases where an implementation has different concept codes from CIEL. For example, if an implementation uses concept code (ID) 1234 for "Negative" instead of 664 like CIEL, then I'm not sure the collection will get imported correctly into OpenMRS (I assume it will either fail or possibly create the link questions to the wrong answers). But this is still a good step in the right direction! Please promote to Production! 🙂

**Comment by jamlung-ri** [comment]
@snyaggarwal Please take this to Production!
