### ISSUE TITLE
Global Dashboard for Authenticated User

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1862]
Similar to the dashboard in #1861, with additional features:
- User nav menu
- Personalized feed

User Story:
As an authenticated user, my landing page on the TermBrowser should help me to access relevant content, highlighted resources, etc.

Design for OCL Online: https://zpl.io/DplDQ6O
Design for other instances: https://zpl.io/KEG08jR
Specification of Feeds/Events: https://docs.google.com/spreadsheets/d/1idF7p-0lYizHTPhYgSoxigM9F9MJpzOUeq-TbR5-abI/edit

Current authenticated Dashboard:
![image](https://github.com/OpenConceptLab/ocl_issues/assets/55999682/93be6bca-b6d0-4382-b02f-b910e7dee767)

**Comment by snyaggarwal** [comment]
@paulsonder @jamlung-ri A dashboard for logged in user is ready for review on QA v3.

**Comment by jamlung-ri** [comment]
Your Recent Activity
* Needs more space between Profile Picture and "Your recent activity" (do we even need the profile pic next to Recent Activity? It seems duplicative from the profile pic at the top right)
* "More" button autoscrolls to the bottom, but it probably should stay where it's at.
* Section can probably span to the entire right side, underneath the Profile Picture that's at the top right

Recent activity
* I tested an event and am not seeing it in the feed. In my organization "DemoOrg", I created a version of a source, but it's not appearing in the main feed on the page. It does appear in the "Your recent activity" section though, which makes sense. Is this intended behavior? 
      * (Note that there are probably multiple Events behaviors to work through but I don't know if now is the best time.)

Current empty state:
![image](https://github.com/user-attachments/assets/2d6c7d09-ef7a-461f-acf5-7163964507b9)

Current state with some events:
![image](https://github.com/user-attachments/assets/b16abb72-dea4-4489-8f97-48ad5e02a86d)

**Comment by snyaggarwal** [comment]
Hey @jamlung-ri 
1. Fixed spacing between Profile Picture and "Your recent activity". 
2. "More" button autoscrolling to bottom is intentional. @paulsonder Can you please check this behaviour and let us know we if need to adjust it.
3. The entire dashboard is limited to specific width from designs. I have increased to 1440px now. @paulsonder Need your input here as well.

4. @jamlung-ri If you "follow" the repo version, it would appear in your main dashboard feed in "All" and "Following", otherwise its just a user event. Its also not an "org" event because we are not showing org's repos events inside org, so even if you are a member of the org it wont show up in your "Organizations" events.

**Comment by jamlung-ri** [comment]
@snyaggarwal One quick addition (still doing testing):

- [ ] Hyperlink all resources in the Recent Activity feed so that I can navigate to the owner/repo/whatever. See example here, where I can see that Paul followed CIEL but I cannot click on it to go to the CIEL org.
![image](https://github.com/user-attachments/assets/11a5ace8-d799-44c6-80b0-bb4e3737e013)

**Comment by snyaggarwal** [comment]
@jamlung-ri This is done

**Comment by snyaggarwal** [comment]
Closing this ticket. Lets create specific tickets for feedbacks and bugs.
