### ISSUE TITLE
Detail view: Mappings

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1952]
User interfaces can be found [here](https://zpl.io/n6ozLpY).

Please record any feedback that needs to be actioned before moving the Dev here.

For future requirements, let's capture in a separate ticket and prioritise accordingly.

**Comment by jamlung-ri** [comment]
Jon and I both agree that this is looking a lot better, so I think we can move it forward into Ready for Dev!

**Comment by jamlung-ri** [comment]
Thanks Sunny! This is feeling really good to use! So much easier than v2, I think. Putting feedback below:

- [ ] (Question for @paynejd) Sort weight does not appear in the Mapping Details pane, but I forget if that's intentional or not. I feel like it should be included, but perhaps with a suffix to "See concept [id] for sorted list" or something like that.
- [ ] This may be negligible but the transition between mappings is so fast that sometimes I'm unaware that the Mapping Details page actually updated to the latest mapping I selected. @paulsonder Could you look at this and see if this actually matters or not? It might be me just not used to V3, or maybe a simple transition would help.
- [ ] A hover tooltip is still appearing on the source, even when the source doesn't actually exist in OCL. If OCL can't resolve the concept or source, then no hover tooltip should appear. [Example mapping with unresolved stuff here](https://app.v3.qa.openconceptlab.org/#/users/jamlung/sources/test/mappings/1792951).
- [ ] If either of the mapped concepts don't resolve, you end up on OCL's homepage if you click on the concept box. For both sources and concepts, if OCL can't resolve it, then it shouldn't have a hyperlink on it.
- [ ] The mapping source text is getting truncated. This makes sense so that the little box doesn't get too long, but the user will need to be able to see the full text somehow (maybe a simple text tooltip on hover if the source itself isn't resolving?)
![image](https://github.com/user-attachments/assets/fc9a740f-458a-49bf-82cb-fc7dea8baad5)


Also including some notes that likely do not need to be addressed here:
* (This likely belongs in #1960) The Source preview tooltip should show the source's Short Name or ID, not the relative URL - see screenshot

![image](https://github.com/user-attachments/assets/4837773b-e1ab-499a-997d-1b31598bbb89)

* Custom attributes do appear with a `Custom` tag (see screenshot)

![image](https://github.com/user-attachments/assets/13ddc217-ac7b-4b18-adc3-95113afbc9a4)

**Comment by paulsonder** [comment]
@jamlung-ri Regarding the transition when clicking resources and the Detail view is already open.

I will create a new ticket for this. It could be improved but lets figure it out later.

**Comment by jamlung-ri** [comment]
@paulsonder @snyaggarwal This mapping view is almost done. Just a couple of (hopefully) small things below.

- [ ] Jon gave some feedback about checksums and how they aren't helpful in the Properties section. @paulsonder Do you think we can move that into somewhere else in the Mapping Detail view? Maybe underneath Last Updated or something? Jon gave this example from GitHub's checksum if it helps. 
![image](https://github.com/user-attachments/assets/363dd483-c8dd-42d5-a556-f6a9420c2903)

- [ ] The Properties section will not be used for checksums, but should still appear if there are Extra attributes on the mapping, which isn't very common but definitely possible. Up to @paulsonder if there should be an empty state for the Properties table or if it shouldn't appear without Extra attributes present.

Requirement for future (which will get its own ticket): When a mapping has a sort weight, show its From concept plus the sorted list of Target concepts below the mapping.

**Comment by paulsonder** [comment]
@jamlung-ri Is it important to indicate if there is no sort weight? If not, I would say we can hide the Properties panel.

The Checksum has been updated to sit in the footer in Zeplin. Is there anything else that is useful to display there?

**Comment by snyaggarwal** [comment]
@paulsonder There are two checksums -- standard and smart. Should we add both at the bottom with respective labels?

**Comment by snyaggarwal** [comment]
@jamlung-ri @paulsonder 
1. Moved Standard/Smart checksums to the bottom (both concept and mapping)
2. Added Sort weight in properties
3. Hiding properties section if nothing is there to display

**Comment by paulsonder** [comment]
> @paulsonder There are two checksums -- standard and smart. Should we add both at the bottom with respective labels?

Thanks @snyaggarwal

**Comment by jamlung-ri** [comment]
@snyaggarwal @paulsonder I think this is looking good in its current state! I went ahead and made another ticket for displaying the list of sorted concepts too, so we should be good here.
