### ISSUE TITLE
Repo: Versions

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1955]
User interfaces can be found [here](https://zpl.io/WQ47Xde).

Zeplin includes two views of the Version picker and list, with no version selected, but current version a user is viewing highlighted and with more than one version selected, meaning they can click to compare.

**Note:** the versions tab was depreciated in favour of ensuring versions are positioned in the page hierarchy in such a way that the content below inherits whatever value is selected. That means the picker needs to include more information than in v2, so as to function as a useful list as well as a menu.

Download, copy and 'explore' would be accessible via the buttons in the Repo if a version is selected from a list. 

Please record any feedback that needs to be actioned before moving the Dev here.

For future requirements, let's capture in a separate ticket and prioritise accordingly.

**Comment by jamlung-ri** [comment]
@paulsonder I have no further feedback on this design, so I'm going to move it forward to Ready for Dev!

**Comment by paulsonder** [comment]
@snyaggarwal Moving to **'Ready for dev'** - let me know if you would like to schedule some time to discuss.

**Comment by jamlung-ri** [comment]
@snyaggarwal A couple of issues here: 

1. Here is the state when a [Private version](https://app.v3.qa.openconceptlab.org/#/users/jamlung/collections/openmrs-demo/private/) is selected. There does not appear to be a way to get back to the collection versions I have access to, unless I use the browser's Back button. Can we persist the breadcrumb and Header for this state?

![image](https://github.com/user-attachments/assets/20baeaa3-2127-4710-8773-dd6341dc2cf2)


2. When there is no default expansion for a collection version, OCL displays two icons but no numbers. Would it make sense to put some placeholder text instead of the empty icons? E.g. "N/A" and if the user hovers, the text tooltip shows "No default expansion for this version". Open to feedback or other ideas.

See the screenshot below, which is happening in this collection: https://app.v3.qa.openconceptlab.org/#/users/jamlung/collections/openmrs-demo/

![image](https://github.com/user-attachments/assets/1ebaeb01-27ce-4903-a91b-57a4c269f2a8)

**Comment by snyaggarwal** [comment]
@jamlung-ri 
1. Added 403 state for this. Persisting header and breadcrumb is difficult since its the entire page that cant be accessed by the user. I have added "back" button link in 403 page, hope that helps.
2. Fixed the summary in versions table, if its not calculated then it will show empty cell.

**Comment by paulsonder** [comment]
@jamlung-ri @snyaggarwal 

Is it not possible to prevent a user accessing a private repo at the point of viewing it in the menu? For example, by showing a dialog instead with some information about why they can't see it?

**Comment by snyaggarwal** [comment]
@paulsonder Thats possible, but we still need 403 because the user can directly type in the URL. Right now one solution is handling both situation.

**Comment by snyaggarwal** [comment]
Adding this to our dev call agenda today

**Comment by snyaggarwal** [comment]
@jamlung-ri @paulsonder Added a fix to now allow private (without access) versions to be selectable

**Comment by jamlung-ri** [comment]
@snyaggarwal Good work, everything here seems to be working really well. The only issues I notice is more with the breadcrumb than with the Version selector, but I didn't see a ticket for breadcrumb. Maybe this should go in the #1871 ticket?

* The breadcrumb buttons for Owner and Repo are showing a skeleton-like loading state, but I don't actually know what it's loading.
* Question for @paulsonder : should the repo breadcrumb be showing the repo's Type (e.g. Collection Version or Collection) or it's source_type / collection_type (e.g. Dictionary, Interface Terminology, etc.)? Note that these might end up being one and the same once we implement the Repo Type work, so this question might not matter much.

![image](https://github.com/user-attachments/assets/dfb91c87-5c50-47bf-a804-77c30b664bb9)

**Comment by paulsonder** [comment]
The designs are intended to display the 'hard' type as we defined in the OOUX phase...

- Source
- Collection
- ConceptMap
- ValueSet
- CodeSystem

I think it's important users understand these (or at least the ones they need to interact with). If there are additional labels, let's consider how to display these separately - that would be my preference.

**Comment by snyaggarwal** [comment]
Closing this ticket. Lets create specific tickets for feedbacks and bugs.
