### ISSUE TITLE
Add feature to exclude retired concepts and/or mappings from exports

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#22]
This is especially pertinent for client applications that do not keep track of retired resources (such as OpenMRS for mappings). Note that separate cached exports would have to be created if supporting this.

**Comment by cassiemorgan11** [comment]
The addition of this feature would be incredible helpful. Editing the export after is cumbersome in general, but especially for large dictionaries.

**Comment by paynejd** [comment]
Discuss on future OCL Architecture call if we want to provide additional export options that apply a filter. Note that we could consider providing this functionality in the ocldev2 package as well to that this can be accomplished programmatically.

**Comment by rkorytkowski** [comment]
@snyaggarwal could you please point to a file in codebase where this change should be done to make it easier for new comers?

**Comment by snyaggarwal** [comment]
the method to export -- https://github.com/OpenConceptLab/oclapi2/blob/41cf8ad5cdc81e565d8db9e6ab7a345b130dd063/core/common/utils.py#L193

[concept queryset should change here](https://github.com/OpenConceptLab/oclapi2/blob/41cf8ad5cdc81e565d8db9e6ab7a345b130dd063/core/common/utils.py#L208)
[mapping queryset should change here](https://github.com/OpenConceptLab/oclapi2/blob/41cf8ad5cdc81e565d8db9e6ab7a345b130dd063/core/common/utils.py#L209)

**Comment by PatrickCmd** [comment]
As @snyaggarwal pointed to where the querysets should change, so I think they should be a filter like this

```
concepts_qs = version.concepts.filter(retired=False)
mappings_qs = version.mappings.filter(retired=False)
```

**Comment by snyaggarwal** [comment]
Yes @PatrickCmd you are right. The only other thing is, it should be an optional feature. Users should be able to optionally ask to exclude retired concepts/mappings.

**Comment by PatrickCmd** [comment]
@snyaggarwal is this option to be passed as a parameter in the `write_export_file` function and if yes, is it `boolean` and what would be it's appropriate name.

**Comment by snyaggarwal** [comment]
@PatrickCmd We are expecting to make use of our existing parameter for this `INCLUDE_RETIRED_PARAM` from requests query params.

**Comment by PatrickCmd** [comment]
@snyaggarwal I have raised PR https://github.com/OpenConceptLab/oclapi2/pull/14, please review.

**Comment by snyaggarwal** [comment]
@PatrickCmd Left a [comment](https://github.com/OpenConceptLab/oclapi2/pull/14/files#r681575999)

**Comment by jamlung-ri** [comment]
Default behavior: export file has everything. Now we want to exclude 'retired', so the default behavior will be the same, and then we can exclude the retired.

Two changes needed: 
1. API to perform export is POST and url to export, but now we can take an optional parameter like include/exclude retired
2. UI will need a switch

Need to update Swagger documentation, and Web too. Follow-up tickets to be created for this.

**Comment by PatrickCmd** [comment]
@snyaggarwal I did address your comment on the PR, please review and give feedback if any.

**Comment by snyaggarwal** [comment]
_<<From dev call>>_

We want to support multiple types of export for a version, right now it will be 2. 
**Note: In the future, we may take a different approach to handle this, but for now, this is the shortest path to accomplish this.**
1. `POST /orgs/CIEL/sources/CIEL/export/` and `POST /orgs/CIEL/sources/CIEL/export/?includeRetired=false` are both valid, but they will create two different export files and cache it on S3.
2. POST /orgs/CIEL/sources/CIEL/export/ can keep working as is, no change required in the filename for this. Also same goes for POST /orgs/CIEL/sources/CIEL/export/?**includeRetired=true**
3. `POST /orgs/CIEL/sources/CIEL/export/?includeRetired=false` needs to create an export file excluding retired concepts/mappings and the filename should reflect that -- CIEL_v1_non_retired_<timestam>.zip
4. `GET /orgs/CIEL/sources/CIEL/export/` needs to work as is, look for CIEL_v1_<timestam>.zip in S3.
5. `GET /orgs/CIEL/sources/CIEL/export/?includeRetired=false` needs look for CIEL_v1_non_retired_<timestam>.zip in S3 otherwise return 404.
6. delete version should delete both the export files from S3 (currently it deletes the export file).

**Comment by PatrickCmd** [comment]
I have added the implementation to address the above approach. Though I have found that I have issues with elastic search and my web UI loads with errors. So I have not tested it thoroughly. @snyaggarwal please take a look.
