### ISSUE TITLE
collectionType filter uses an incorrect parameter and returns global search results for an org

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#251]
The Collection type filter should be `collectionType` (not `collection_type`). This filter appears to work correctly for global search (eg `/collections/`). However, it incorrectly returns global search results when a filter is added to the collections within a specific owner. For example, this correctly returns 193 collections within the PEPFAR-Test7 org:
```
https://api.staging.openconceptlab.org/orgs/PEPFAR-Test7/collections/
```
However, when I add the `collection_type="Code+List"` filter, 297 results are performed:
```
https://api.staging.openconceptlab.org/orgs/PEPFAR-Test7/collections/?collection_type="Code+List"
```
This is the same result as performing the global search with the same filter:
```
https://api.staging.openconceptlab.org/collections/?collection_type="Code+List"
```
For this ticket, lets add the filter parameter `collectionType` so that it has the same exact behavior as `collection_type`. We'll support both parameters for now so that we don't break any existing queries. Let's also make sure that the filter is applied correctly and only returns collections owned by the org/user.

**Comment by paynejd** [comment]
also see #135 - these seem like related tickets

**Comment by harpatel1** [comment]
It is determined that the collection_type filter is working as expected just the value of 'num_found' is incorrect, however if you see the value of 'num_returned' it would show the correct number of result. By looking at the code, it seems like the issue is due to incorrect solr indexes and most likely be resolved if we rebuild solr indexes in STAGING environment. 

We are going to add support for 'collectionType' filter which would behave same as 'collection_type' filter.

**Comment by aprilcurrier** [comment]
Need to verify it this works in QA. Dev is 100% Complete @paynejd  to follow up

**Comment by harpatel1** [comment]
I have verified that this works in QA.
