### ISSUE TITLE
Confusing error message when assigning duplicate OCL ID

### ISSUE THREAD

**Issue by ibacher** [OpenConceptLab/ocl_issues#309]
I'm raising this to report [this issue](https://issues.openmrs.org/browse/OCLOMRS-876) to the appropriate place. When trying to add a concept with a duplicate id to the same source, the error message is quite opaque. The error returned from the API is:

 > Concept with this Mnemonic and Parent id already exists.

The error message originates from violating the constraint specified [here](https://github.com/OpenConceptLab/oclapi/blob/67a8b9f3f00acfd3bfc04cc7b87fa97a7d616d8d/ocl/oclapi/models.py#L202). The error message is confusing because both `parent_id` and `mnemonic` are internal OCL concepts not exposed through either the UI or the REST API.

A better message might be "Concept id is not unique for this source" or something similar.

Although I haven't tried it out, a brief review of the code looks like this might apply to oclapi2 as well as oclapi1, since [a very similar `unique_together` constraint exists](https://github.com/OpenConceptLab/oclapi2/blob/57997adf34e40946368f9b6500cced96aaa36e07/core/concepts/models.py#L85).

**Comment by paynejd** [comment]
Thanks for reporting this @ibacher! Agree that is a difficult error message to understand!

Since we are retiring oclapi v1 shortly, we probably will only modify this in oclapi2.

@snyaggarwal -- do you want to take a look at this? I'll create a ticket for us to review other error messages as well.

Suggest a slight modification to what Ian suggested:
"Concept ID must be unique within a source."

**Comment by snyaggarwal** [comment]
done
