### ISSUE TITLE
Feedback on oclweb2 - round 2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#466]
First round implementation of oclweb2 search was captured in #413. This ticket will capture the next round of work.

**Comment by jamlung-ri** [comment]
When on [this page](https://qa.aws.openconceptlab.org/#/orgs/PEPFAR-Test10/sources/MER/concepts/PrEP_CURR/) and clicking on a mapping ([example](https://qa.aws.openconceptlab.org/#/orgs/PEPFAR-Test10/sources/MER/mappings/MAP_REFIND_DE_PrEP_CURR_W4BGn0YggH0/)), the page crashes. It looks like this is because the concept/version is being returned twice, but maybe it's another issue.

**Comment by snyaggarwal** [comment]
@jamlung-ri This is fixed.

**Comment by paynejd** [comment]
Compiling feedback here (note that this is in progress and not prioritized):
https://docs.google.com/document/d/1B10WDBvuEZojNh1XGhHSJUkkWs_yLiZZDInR4dRZSzU/edit#

**Comment by jamlung-ri** [comment]
For the feedback that Sunny has already addressed, I am going through the document, verifying the fix, and crossing it off.

**Comment by jamlung-ri** [comment]
50% or more completed. Development work remaining is ~80%

**Comment by jamlung-ri** [comment]
This [feedback document](https://docs.google.com/document/d/1B10WDBvuEZojNh1XGhHSJUkkWs_yLiZZDInR4dRZSzU/edit#heading=h.q88keq70moyc) should be followed up on, since it has some filter syntax notes.
