### ISSUE TITLE
[Infra] [Terraform] Change in autoscaling launch config doesn't affect autoscaling group.

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#538]
Changing ami_id or instance_type (or anything) in Autoscaling Launch Config doesn't affect ASG.
It just creates a new Autoscaling Launch Configuration.
for example, I updated the `instance_type` from `t3a.large` to `t3a.xlarge`, but it dint affect ASG. It only created a new launch configuration, so the new instances will use that launch configuration but the existing one won't be replaced by this new launch configuration.
The issue is described here in detail with a solution -- 
https://stackoverflow.com/questions/40985151/auto-scaling-groups-dont-update-on-launch-configuration-change
https://stackoverflow.com/questions/39345609/how-to-recreate-ec2-instances-of-an-autoscaling-group-with-terraform

@rkorytkowski is this something you already have in your bucket to fix?

**Comment by paynejd** [comment]
@rkorytkowski @snyaggarwal is this ticket done?

**Comment by paynejd** [comment]
Is this already done?

**Comment by rkorytkowski** [comment]
Added rolling upgrades of instances to ASG. The expected behaviour is to:
1. Bring up one new instance at a time,
2. Send a termination signal to the old instance
3. Bring services on the old instance down
4. Bring services on the new instance up
5. Bring down the old instance
6. Repeat 1-5 until all instances replaced

There's a short downtime expected between 3rd and 4th step (1-10 minutes). It is possible to avoid the downtime, but it requires more work and setting up lambda and SNS as described here: https://aws.amazon.com/fr/blogs/compute/how-to-automate-container-instance-draining-in-amazon-ecs/ 
I'll create a separate issue for that.
