### ISSUE TITLE
[OCL UI 2] Mappings table in Concept Details view should show target source

### ISSUE THREAD

**Issue by djazayeri** [OpenConceptLab/ocl_issues#630]
Go to https://app.qa.aws.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/117399/details/ and look at the mappings table.

Visually it looks like the codes 86491, I10, 38341003, 903 are in the CIEL / CIEL namespace. The "Source" column shows which source the mapping _belongs_ to. But it would be more intuitive and relevant to the end user to show the Source the mapping _points_ to, next to the code in that source.

**Comment by paynejd** [comment]
Hey @djazayeri- Thanks for sending some feedback!

Agree with you on this- for the `Mappings` list, let's show the `to_owner` / `to_source`, since the `from_owner` / `from_source` is the same as the concept page you are looking at.

For the `Inverse Mappings` list, flip it -- show the `from_owner`/ `from_source`

**Comment by snyaggarwal** [comment]
@djazayeri @paynejd this is done.

**Comment by djazayeri** [comment]
Looks good to me. (I don't know who's supposed to close this bug. I suggest someone else does because I don't consistently check my github notifications.)

**Comment by snyaggarwal** [comment]
I feel the creator should close it!

**Comment by paynejd** [comment]
Ha generally agree with @snyaggarwal but I'll close this out because I just tested and is now working great. Thanks again @djazayeri !
