### ISSUE TITLE
Make behavior of search modifier buttons consistent

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#648]
We want the entire search modifier button to be clickable, to show the clickable "pointer" mouse cursor, to highlight slightly on mouse over (like the "Include Retired" button), to have the same colors (there is currently a mixture of dark gray and blue buttons), and to have a descriptive tooltip (eg. the Source/Collection Version selector does not have a tooltip).

Also, we're also getting inconsistent results across different browsers (try selecting "More Filters" on Safari!).

For example, in global search on Chrome and Safari, the "All Time" modifier is only clickable on the "All Time" label (not on the icon) and the mouse cursor shows the "text selector" rather than the "pointer".

On Safari, the "More Filters" button usually shows the "text selector" and it does not respond when clicked.

**Comment by snyaggarwal** [comment]
@jamlung-ri:
#### Added Following:
1. "All Time" button cursor to be always a pointer
2. "More filters" button when disabled cursor should be not-allowed otherwise always pointer
3. Version Button to have tooltip "Change Version" (@jamlung-ri Let me know if this text needs to be updated)
4. Include/Exclude retired filter control to have a tooltip.

#### Comments:
1. The blue/black/gray colors are denoting states of controls:
    - Blue (primary-color) -- Active or Applied (for example by default Row View and PageSize controls are active and blue)
    - Black (secondary-color) -- Not Applied (for example by default Include Retired controls is inactive and black)
    - Gray (tertiary-color) -- Disabled (for example orgs listing "More Filters" is disabled)
@jamlung-ri Let me know if any of the above color behavior needs to be changed.
2. More filters worked exactly the same for me in Safari. @jamlung-ri Can you add a bit more to this?

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd This should be resolved, please verify this.

**Comment by paynejd** [comment]
resovled
