### ISSUE TITLE
Reference Indicator Collection version issue

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#684]
@jamlung-ri commented on [Wed Jan 27 2021](https://github.com/pepfar-datim/DATIM-OCL/issues/833)

Figure out how reference indicator collections will show the correct reference indicators and the correct versions

---

@jamlung-ri commented on [Wed Mar 24 2021](https://github.com/pepfar-datim/DATIM-OCL/issues/833#issuecomment-806031149)

Transferring over to OCL Issues repo under MSP v1 epic

---

@jamlung-ri commented on [Wed Mar 24 2021](https://github.com/pepfar-datim/DATIM-OCL/issues/833#issuecomment-806032748)

Should be addressed in PEPFAR-Test10b import. Will be validated by @jamlung-ri , then we will decide whether to close or transfer this ticket.

---

@jamlung-ri commented on [Fri Mar 26 2021](https://github.com/pepfar-datim/DATIM-OCL/issues/833#issuecomment-808427457)

@paynejd At first glance, this seems to be working now, but one issue I am noticing is that in this [FY21 collection](https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10b/collections/MER_REFERENCE_INDICATORS_FY21/concepts/?limit=999&verbose=true), there are FY16 versions of reference indicators. In this collection, PrEP_NEW is an FY16 version, which has a `Reporting frequency : "Annually"`, but the FY21 version of PrEP_NEW in the [import spreadsheet](https://docs.google.com/spreadsheets/d/1_z6JJN-wC8H5hhtJPK6lB89IKOl7TLDdQcpiazbZQgk/edit#gid=803804598) has `Reporting frequency : "Quarterly"`. How do you suggest we address this? I wonder if these collections are now storing the oldest versions of each Reference Indicator, rather than the most recent.

Meanwhile, @FelixOngati one quick change to MSP is needed. The Reference Indicator page should no longer use the API filter “extras.Period=FYxx”

**Comment by paynejd** [comment]
I did some digging into the references that are not showing up correctly for PEPFAR-Test10b. Interestingly, they are 100% correct on staging.aws, but there are 150+ errors on qa.aws. The primary issue is that some collections are supposed to reference updated versions of the concepts, but instead the references are all pointing to the original version of the concept.

It appears that what happened is that in qa.aws, the concepts actually didn't update at all during the bulk import. See how QA has only one version but staging has several for the same concept:
* QA: https://api.qa.aws.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/concepts/PMTCT_ART/versions/
* Staging: https://api.staging.aws.openconceptlab.org/orgs/PEPFAR-Test10b/sources/MER/concepts/PMTCT_ART/versions/

Also ran into a couple of other issues. We had a chance to discuss all during the architecture call today, so just listing next steps here:

- [ ] Investigate logs on qa.aws to understand why concepts did not update [Sunny]
- [ ] Import PEPFAR-Test10b on qa.aws again (after the first one is done)
- [ ] Modify collection behavior so that expressions are saved in the collection as they are submitted, rather than as an expression that was already resolved to a specific concept version. Expressions for a single concept (and same applies for mappings) may be submitted in 3 ways: version-less, source versioned (eg /CIEL/v2021-03-12/) or concept versioned. These should be resolved upon request if in HEAD or resolved when saved to a collection version.
- [ ] Fix missing attributes and incorrect `id` attribute for collection versions (see separate ticket)
- [x] Retrieving concepts via a collection results in 409 Conflict even when there is no conflict

**Comment by jamlung-ri** [comment]
I rechecked the newly updated PEPFAR collections, and they seem to be showing the correct versions now!

**Comment by paynejd** [comment]
final task moved to #702
