### ISSUE TITLE
Getting a list of queued bulk imports shows inconsistent results

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#703]
```
GET https://api.staging.aws.openconceptlab.org/manage/bulkimport/
```
This query should return a list of the following for the default queue and for any custom queues:
* Recently processed bulk imports (regardless of `SUCCESS` or `FAILED` status) -- in the last 24 hours?
* Bulk imports currently being processed (`STARTED`)
* Bulk imports that are queued for processing (eg `PENDING` or `NOT STARTED`)

The current behavior is that it typically shows only imports that have completed within a few minutes or those that are currently being processed. After a few minutes, completed imports are no longer returned unless requested individually with a specific `task` ID.

We want this behavior to be consistent for the other import endpoints as well

**Comment by snyaggarwal** [comment]
@paynejd @rkorytkowski I found few interesting things with Flower API. 
1. Flower API (/api/tasks) returns 10000 tasks result.
2. They recently had a pull request to do pagination which they merged in master, but it's buggy.
3. Flower API has a way of filtering tasks in API by name (?taskname=). But it doesn't accept wildcard queries.

This answers a part of this issue, where if you queue a bulk import (which may be large) and query the list of import tasks it may return a list but that changes if the total tasks exceed 10k. In that case, you will not get the same list since it's by default sorted with task start DateTime in desc order. (which is the problem statement of this issue)

The short term solution of this is to query tasks by taskname `?taskname=core.common.tasks.bulk_import` and `taskname=core.common.tasks.bulk_import_parallel`. This I have tried and it works. It will keep on working until we hit the limit of 10k tasks of each bulk_import type (which is pretty huge).

The long-term solution is to use the DB backend which we have discussed.

Let me know if this makes sense
