### ISSUE TITLE
Add two accounts in QA and Production 

### ISSUE THREAD

**Issue by suruchee** [OpenConceptLab/ocl_issues#738]
Two accounts are needed in both QA and Production. So, can we have accounts like admin/Admin123 and user/User123 in OCL?

**Comment by snyaggarwal** [comment]
@suruchee Signup should work on both environments, you will need a stronger password.
Let me know if you are unable to signup in either environment.

**Comment by suruchee** [comment]
@snyaggarwal I am able to log in with my OCL login, but it would be to use the admin credential.

**Comment by snyaggarwal** [comment]
@suruchee I dint quite understand. In order to create new accounts/users, you can just signup multiple times with different email-ids on either of the environment. You don't need to login first.
Right now there is no way to create an account with admin privileges via UI. That has to be done via API.
