### ISSUE TITLE
Update URL as user navigates tabs/resources and searches in the TermBrowser

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#809]
This would be helpful to be able to share links that take people to a specific search/tab/resource. It might also make reloading the page or going back a page more predictable

**Comment by bmamlin** [comment]
### Some common use cases

* I want to share a search with someone by sharing a link to the search (ideally would include all filter settings and current position/page, so after clicking the link they will see the same results I am seeing)
* I create or delete a version of a source, when the page auto-reloads, I stay on versions tab instead of switching to concepts (first) tab
* I am on any tab other than the first/default, follow a link (e.g., to a mapping) and hit the back button expecting to return to the tab (or search results) I was previously viewing.

**Comment by rkorytkowski** [comment]
@snyaggarwal are you planning to do more work on this?

**Comment by snyaggarwal** [comment]
@rkorytkowski Almost done with this. Should be able to showcase this fully in our next dev call

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd Below tasks were done as part of this.
1. On any action on page URL updates 
2. Get a sharable link by clicking Share button
3. Browser back should take back to the exact previous state with all the actions earlier applied.

Can we close this?

**Comment by jamlung-ri** [comment]
This seems to be working well to me, with the exception of going back to a custom configured tab. Fixing this is not high priority though. Otherwise, the majority of actions are updating the URL.

**Comment by paynejd** [comment]
this is working great
