### ISSUE TITLE
Export of HEAD not yet working as expected

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#817]
When working on publishing CIEL v2021-06-07 on Production (#810), I tried using the new feature to export HEAD directly to JSON.

* I clicked the download icon for HEAD and got the pop-up with an option to start an export
* I clicked on the button to start the export
* The HEAD showed "processing" and the download popup changed to a message that the export was in process.
* Eventually (?hours later), instead of providing a link to download the JSON export file the download popup returned to initial state (providing a button to start an export) which has remained for days:

![image](https://user-images.githubusercontent.com/860834/122796296-374d4f80-d28c-11eb-91ca-54cfa3365944.png)

Perhaps something happening during the export process is being seen as a change so the export can never finish? Or maybe there's just a bug in the process.

**Comment by snyaggarwal** [comment]
@bmamlin The reason it didn't work because it was doing too much and the job hung around for too long and got killed with deployment :(
I have fixed the concepts/mappings query for HEAD (it was fine for other versions). Also. I tried to create and export on Prod for the CIEL HEAD version and it was successful in 47 minutes. 
You can download it from there or delete the export using:
DELETE https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/HEAD/export/
and create a new one to test this again.

**Comment by jamlung-ri** [comment]
Burke said this is working fine.
