### ISSUE TITLE
Create dev environment for concept modification epic

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#837]
To confirm that this is the right approach

**Comment by rkorytkowski** [comment]
@snyaggarwal do you think we should work on a branch for #816 and have a dedicated environment to test it?

Can you think of a way to avoid that and work on it in master without affecting releases?

**Comment by snyaggarwal** [comment]
@rkorytkowski It will be very hard to keep code clean and support both current and new models within the master. Feature toggle will also not help in this due to schema changes as well, keeping this on a branch will make things much easier. And yes an environment to test/try this out will be needed after some initial work is done.

**Comment by rkorytkowski** [comment]
@snyaggarwal all right. I'll add a new environment then.
