### ISSUE TITLE
Unable to filter by multiple concept classes and/or datatypes on this endpoint: https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts

### ISSUE THREAD

**Issue by collinewait** [OpenConceptLab/ocl_issues#88]
I have tried to filter out *test* and *drug* concept classes, but returned results contain only concepts having *Test* conceptClass and those with *Drug* conceptClass are not returned as shown below:

`https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/?q=&conceptClass=test,drug`
<img width="1224" alt="screenshot 2019-02-06 at 13 51 51" src="https://user-images.githubusercontent.com/21334508/52336699-a35dee80-2a16-11e9-9aa2-b3cbe07521d5.png">

I think it should work in a similar way to this: `https://api.qa.openconceptlab.org/users/admin/collections/d3h7d3e4g6d3e4/concepts/?q=&limit=0&page=1&verbose=true&conceptClass=test,drug`

**Comment by rkorytkowski** [comment]
@paynejd, it seems like something we want to address?

**Comment by paynejd** [comment]
Rafal- yes let's definitely address this -- possible for you to prioritize?
I had seen some issues with the search results too, but hadn't checked into
it yet.

**Comment by rkorytkowski** [comment]
Just tested it. The drugs do appear in results, but since there are more results and default limit is 10 items, you need to paginate to the 12th page or higher e.g. 
https://api.qa.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/?q=&conceptClass=test,drug&page=12

You can also adjust limit for a single page with &limit=50. The number of matched items can be found in the num_found response header.
