### ISSUE TITLE
CSV Import of Booleans

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#954]
To allow import of boolean attributes via CSV, users should be able to specify the type of value in the column header. Example: `attr-bool:precise` is a boolean attribute called "precise"

**Comment by gracepotma** [comment]
Update from Michael B: When True/False is changed to TRUE/FALSE (e.g. here: https://github.com/DWB-eHealth/msfocp-source/blob/main/OCL_SourceImport_TestCases.csv), the concept is now being imported.

**Comment by bmamlin** [comment]
It would be worth thinking about the data types (beyond boolean) when adding this feature. Not necessarily to say they all need to be supported, but at least to make sure the convention we adopt for specifying boolean will work for the other data types we plan to support in the future. For example:
* boolean
* string
* number (or do we distinguish int, float?)
* date (do we need/want to support date, time, timestamp?)
* arrays (e.g., comma-separated list of other data types)

I understand the approach of `attr-bool:name` might be easiest to implement. Since these are CSV headers and likely truncated in spreadsheet displays, would it be better to switch to `name:attr-bool` so people viewing the data in a spreadsheet will see a truncated name instead of a truncated datatype for column headers?

**Comment by snyaggarwal** [comment]
@paynejd Please review the pull-request https://github.com/OpenConceptLab/ocldev/pull/12

**Comment by snyaggarwal** [comment]
@paynejd I have tested this with empty values and they don't make it through

**Comment by paynejd** [comment]
data_types = ['bool', 'str', 'int', 'float', 'list']

**Comment by jamlung-ri** [comment]
Ready to close out. Just need to put this into documentation.

**Comment by jamlung-ri** [comment]
@paynejd Here is an example CSV bulk import file that uses List, Boolean, Float, and Int types. It has been loaded in [here](https://api.demo.openconceptlab.org/orgs/DemoOrg/sources/MyCSVSource/concepts/Act/?verbose=true).

[Working Formats Test OCL CSV Import Example.csv](https://github.com/OpenConceptLab/ocl_issues/files/7243972/Working.Formats.Test.OCL.CSV.Import.Example.csv)

One small note - trying to put a float (e.g. 2.5) into an int field makes the import fail.

**Comment by jamlung-ri** [comment]
Documentation has been updated with an updated CSV example. See here: https://docs.openconceptlab.org/en/latest/oclapi/apireference/bulkimporting.html#csv-format-example
